### ISSUE TITLE
SnoopWPF on "Disabled" control state? 

### ISSUE THREAD

**Issue by psimla** [snoopwpf/snoopwpf#108]
I use 2.10 version.

How can I snoop on "Disabled" control state?

**Comment by batzen** [comment]
I don't get your question.
Could you explain what you mean a bit more?

**Comment by psimla** [comment]
Normally, When I press Ctrl+Shift and drag mouse over to the control. red border will appear at the control, right?

![cannnot snoop on create button](https://user-images.githubusercontent.com/2641121/49208129-8212cd80-f3e9-11e8-9be0-b976d6042df7.png)

But,
I have Buttons, TextBoxes that set IsEnabled property value to False. In this case "CREATE" Button.

When I do the same steps as above. Red border does not appear on those controls.

What is your recommendation?

Sorry, for my English.
