### ISSUE TITLE
Doesn't find PresentationSource hosted in CustomTaskPane (ElementHost) in Office VSTO Add-in

### ISSUE THREAD

**Issue by HamletHakobyan** [snoopwpf/snoopwpf#116]
Hi,

Snoop can't find PresentationSource that contains WPF control. I did some investigation and it is not the case which was related to Wpf controls hosted in ElementHost of WinForms window.
The issue arises by specificity of Office VSTO Add-in which loads in its own appdomain.
PresentationSource.CurrentSources can't enumerate sources from another appdomain which is caused the issue.
Attached minimal project for repro. 
[SnoopTestAddIn.zip](https://github.com/cplotts/snoopwpf/files/2702117/SnoopTestAddIn.zip)

**Comment by HamletHakobyan** [comment]
Hi guys, any news?

**Comment by batzen** [comment]
I've got a"working"version on my machine. I just need time to finish it and i am not sure if this will work on .net core 3.0. But we could just disable the feature .net core if it's not possible there.

**Comment by HamletHakobyan** [comment]
Hi @batzen , good new. Don't worry about .net core. VSTO available only for .net framework.

**Comment by batzen** [comment]
Well the code is not specifically for VSTO but enables snoop to attach to multiple app domains.

**Comment by HamletHakobyan** [comment]
Hi @batzen , how are you doing? Any news on topic?

**Comment by batzen** [comment]
I am doing fine.
Had to wait for my SettingsTransport PR to be merged as the changes i made there require changes to the cross-appdomain stuff for this issue.
Now that my PR is merged i will make the required changes for this issue till early march as i am on vacation starting tomorrow.

**Comment by HamletHakobyan** [comment]
Hi @batzen , Is there any news regarding to multi-appdomain support?

**Comment by batzen** [comment]
I am currently very busy. Will try to get this done next week.

**Comment by batzen** [comment]
Fixed in 2.11.
