### ISSUE TITLE
Screenshot feature produces pixelated low-res image for larger windows

### ISSUE THREAD

**Issue by djkrose** [snoopwpf/snoopwpf#120]
Isn't the screenshot feature supposed to produce high-res images depending on the dpi setting? - Doesn't work for me.
Snoop gives me a crystal clear magnifier zoom and zooms perfectly in the preview area as well, but when I click on the screenshot icon, chose 600 dpi, it produces a pixelated mess. Looks like 96 dpi just upscaled.

For reproduction, I created a simple dummy WPF app, .Net Framework 4.6.1, with just 3 controls.
[WpfApp1.zip](https://github.com/cplotts/snoopwpf/files/2871532/WpfApp1.zip)

My WPF app: Large window, 3 controls...
![wpfapp1](https://user-images.githubusercontent.com/30222867/52893414-2cee8880-319c-11e9-910e-733b723023f7.png)

Perfectly zoomable in preview area
![previewarea](https://user-images.githubusercontent.com/30222867/52893392-ef89fb00-319b-11e9-9f69-ce83048afa6a.png)

Taking screenshot, 600 dpi ...
![save](https://user-images.githubusercontent.com/30222867/52893425-3f68c200-319c-11e9-8f72-0f4818853e83.png)

Result file:
![snoopscreenshot](https://user-images.githubusercontent.com/30222867/52893430-4ee80b00-319c-11e9-9563-94ebba8cf29e.png)

Looking closer into the result file ...
![snoopscreenshot-zoomed](https://user-images.githubusercontent.com/30222867/52893437-5f988100-319c-11e9-9d43-608c870dcb5e.png)

So what is happening here?
When I test with a very small window the end result looks better. Is the actual resolution somehow limited by the screen resolution (1920x1080)? But why does magnifier and preview look so good then?

Tested with Snoop 2.10.0

**Comment by batzen** [comment]
Will have a look when i am back home. But remember that zooming in the magnifier does not zoom an image. It zooms the UI which means it's a vector graphic. When taking a screenshot it produces a pixel based image. You will never get the same zoom quality when comparing vector to pixel images.
Taking a screenshot of a single control should be possible though. Have you tried that?

**Comment by djkrose** [comment]
I know, I was thinking that the screenshot feature _first_ zooms the vector wpf according to the dpi setting, and _then_ takes that screenshot. What else is the dpi setting otherwise for? That's even what the original contributor claims where I found the feature described first: https://qmino.wordpress.com/2010/09/20/high-res-screenshots-of-wpf-apps/  

Interestingly, the screenshot feature _does_ vector zoom a bit, just not anywhere near the claimed dpi for a larger window. When "screenshotting" the radio button control only, the vector zoom is much better, but it introduces a new problem: The image gets distorted. See how the radio button is not round anymore?

![radiobutton](https://user-images.githubusercontent.com/30222867/52899293-b166f880-31e8-11e9-9dcc-eb14a3d9a44e.png)

Compare that with the tree preview:
![previewradioround](https://user-images.githubusercontent.com/30222867/52899312-e96e3b80-31e8-11e9-94f1-6c551f4f4287.png)

My guess is: The screenshot feature _tries_ to zoom but gets somehow limited by the actual screen size.  If that's a WPF renderer limitation, the magnifier and preview seem not to be limited by it. So a solution could be to take the zoomed screenshot in multiple zoomed parts and stitch the raster image together. Similar as to how high-dpi browser screenshot tools do it (eg. Chrome -> Print full screen).

**Comment by batzen** [comment]
Ok. That looks wrong. Will have a look in about a week.

**Comment by batzen** [comment]
So a week was a bit optimistic.
The screenshots are actually really high dpi which means the image is just create with greater dimensions.
So if you choose 600 dpi and your control has a width of 800px the image will have 5000px.
I still had no time to have a look at the distorted issue you posted.

**Comment by batzen** [comment]
@djkrose i finally found some time to investigate this further and indeed the quality is way below what can be expected when increasing the DPI for the image.
The poor quality is caused by some conversion in the capture code.

**Comment by djkrose** [comment]
Glad you could find it. Thanks for investigating!

**Comment by batzen** [comment]
Finally found a solution.
Using 4800 DPI (left before, right after)
![image](https://user-images.githubusercontent.com/1971030/82761666-79436200-9dfc-11ea-9aa2-6965a66ac67b.png)
![image](https://user-images.githubusercontent.com/1971030/82761689-9aa44e00-9dfc-11ea-927d-bf25212ced13.png)

Just have to do some finishing before i push the code changes.
