### ISSUE TITLE
Fatalexecutionengineerror when a window is hidden.

### ISSUE THREAD

**Issue by EikeStein** [snoopwpf/snoopwpf#124]
In my WPF application I have a hidden Window, that is used to display addition information. I hide and show that window during runtime, but create the window on startup. If try to snoop the app before I've once shown the hidden window, then the app crashes with an Fatalexecutionengineerror-Exception when I try to expand the root-node in Snooper or try to use ctrl+shift to find elements.
This issue is propably related to #100.

**Comment by batzen** [comment]
Will try to have a look at this next week.

**Comment by batzen** [comment]
I can't reproduce your issue with a simple test project.
Which version of snoop are you using?
Could you provide a small repro?

**Comment by batzen** [comment]
@EikeStein ping
