### ISSUE TITLE
how to use Snoop to perform automation tests with WPF UI

### ISSUE THREAD

**Issue by rmcavalcante** [snoopwpf/snoopwpf#125]
Hello guys!

I am really sorry for introducing an issue for asking this kind of information.
I read a post on Stackoverflow where one of the members had successfully used Snoop to perform "unit automated tests" with his UI.
The post did not give any details on how to do so, so I thought it would be a good place to start asking you guys for some blueprints in this direction.
Would it be possible to obtain a sample code showing how to instantiate a test with Snoop and controlling the interface? It could be any interface, as long as we can see how to code a click and how to inspect an answer coming from a processing that has been triggered by a button-click, it would be great.
Thank you all and sorry again for this post that is clearly not an issue, although I would really appreciate an answer.
Have a nice day!

**Comment by batzen** [comment]
I never tried to do something like that with snoop and don't think it's capable of doing that.
Could you add a link to the stackoverflow question?
