### ISSUE TITLE
Snooping crosshairs don't work in Windows Version 10.0.18362 Build 18362

### ISSUE THREAD

**Issue by matthew-a-thomas** [snoopwpf/snoopwpf#130]
The crosshairs for snooping (haven't tried the ones for magnifying) are no longer working for WPF apps in Windows Version 10.0.18362 Build 18362.

I first noticed this a little while back so I'm not sure if this is the oldest version of Windows in which they don't work.

A coworker is also encountering this issue. I'm not sure what version of Windows they are using.

Using https://github.com/snoopwpf/snoopwpf/releases/tag/2.10.0
Confirmed it also doesn't work in 2.9. It did use to work in both these versions of Snoop.

Let me know how I can help debug this issue.

**Comment by batzen** [comment]
This is essentially a duplicate of #128 
I am still unable to reproduce this...

**Comment by batzen** [comment]
Could you add a screen recording showing the issue?
You can use something like screentogif for that.

**Comment by matthew-a-thomas** [comment]
@batzen Sure, here ya' go. There shouldn't be anything unusual about the application shown in this recording. All I did was create a new WPF solution in Rider.

Let me know what other info you'd like. I don't mind debugging Snoop from source code with breakpoints if you need... just tell me where to put them and what to look for.

![Cannot drag snoop crosshairs](https://user-images.githubusercontent.com/14829821/59350479-25726280-8cea-11e9-95bb-c2a931a46d65.gif)

**Comment by matthew-a-thomas** [comment]
> This is essentially a duplicate of #128

I bet you're right. I'm closing this one.
