### ISSUE TITLE
VS 2019 incompatibility?

### ISSUE THREAD

**Issue by knutt** [snoopwpf/snoopwpf#137]
After I upgraded to VS 2019, my dear Snoop has failed me.
When I launch Snoop, the Snoop bar displays, but the dropdown list of available applications stays empty. Clicking Refresh causes Snoop to hang.
Probably an issue with VS2019 compatibility?

**Comment by batzen** [comment]
Which version of snoop are you using?

**Comment by znakeeye** [comment]
Did you try running Snoop elevated? I just noticed that Snoop has stopped working for me when running my process from within Visual Studio 2019. It seems the process is run in another user context or whatever. Weird.

**Comment by batzen** [comment]
There should be no need to run snoop elevated as of the latest version. Snoop is able to detect elevated processes and elevate itself if required when snooping.

**Comment by znakeeye** [comment]
Well, it detects that elevation is indeed required. I know I didn't start VS elevated... That's the weird part :/

**Comment by batzen** [comment]
That's strange. Will see if i can add some logging to that part of snoop.

**Comment by knutt** [comment]
> 
> 
> Which version of snoop are you using?

Good morning :-),
I am using 2.11.0.0.
I will try to run elevated and see. Stay tuned...

-knut

**Comment by knutt** [comment]
1) Running Snoop as admin did not help
2) Also, no difference whether I run my app in debug mode from VS, or a standalone release build.

-knut

**Comment by batzen** [comment]
@knutt Any chance you could provide a a repro for that? If you can't we will have to wait till i get time to add more diagnostics logging to that part of snoop.

**Comment by knutt** [comment]
Hi again @batzen ,
Today, there was an upgrade to Visual Studio, to ver. 16.2.2. After installing this upgrade, Snoop works again!
I don't know if this is a coincidence or not, but I am happy for now :-)
