### ISSUE TITLE
Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by jimfoye** [snoopwpf/snoopwpf#138]
Fresh install of VS 2019 and Snoop 2.11. So, trying to use Snoop for the first time with this configuration. I launched the app from the debugger, and then attempted to snoop it.

Exception details:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Snoop.Shell.EmbeddedShellView..ctor()
   at Snoop.SnoopUI.InitShell()
   at Snoop.SnoopUI..ctor()
   at Snoop.SnoopUI.SnoopApplication()
   at Snoop.SnoopUI.GoBabyGoForCurrentAppDomain(String settingsFile)

=== Pre-bind state information ===
LOG: DisplayName = System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Data/Downhole Software/Projects/LAS Doctor/Source/LasDoctor/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Data\Downhole Software\Projects\LAS Doctor\Source\LasDoctor\bin\Debug\LasDoctor.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.confi

Followed by

![image](https://user-images.githubusercontent.com/4249676/63601330-d3bc4300-c58a-11e9-9dc2-380fd16bf9d9.png)

**Comment by batzen** [comment]
The missing dll might be my fault, the "Can't Snoop" message is strange.
Any chance you could attach your application to this issue?

**Comment by jimfoye** [comment]
Actually I just tried creating a new WPF app and got the same errors. So I don't think there's anything particular about the application. My setup is Windows 7 (fresh install) + VS 2019.

**Comment by batzen** [comment]
Which powershell version do you have installed?

**Comment by batzen** [comment]
And could you try to use the snoop preview version from https://ci.appveyor.com/api/buildjobs/v1uoq4s6p4apl598/artifacts/output%2Fsnoop.3.0.0-alpha0074.zip ?

**Comment by jimfoye** [comment]
Looks like I have 2.0 installed (not surprising, as this is a fresh install of W7). You want me to upgrade it? Or go ahead and try the preview version of Snoop?

**Comment by batzen** [comment]
The lowest supported powershell version is 3.0. The preview also has that limitation but it only loads powershell if you select the powershell tab.
What i am curious about is if the preview also fails to find a presentation root, so it would be nice if you could try it out.

**Comment by jimfoye** [comment]
Tried the preview, but nothing happens. I don't get any errors, but I also can't snoop or magnify the target.

**Comment by batzen** [comment]
Do you have dbgview installed? The preview writes quite some information to the trace output. Will change that to some kind of log in the future. But getting the output it produces on your machine might help finding out what's wrong.

**Comment by jimfoye** [comment]
No. But - should I just upgrade Powershell? If there's a requirement there to do so that's fine with me. I'm just wondering if you want to spend any more time on this if my environment is not set to minimum requirements.

**Comment by batzen** [comment]
Powershell is not a real requirement for snoop, it's just one feature that can be used but doesn't have to. Having no powershell or the wrong version shouldn't prevent snoop from running.
I would be very interested in finding out what's causing your issue with the preview version. If it happens on your machine it can happen on other machines too.

**Comment by jimfoye** [comment]
Ok, is this what you want me to install?

https://docs.microsoft.com/en-us/sysinternals/downloads/debugview

**Comment by jimfoye** [comment]
This might be what you want...


[4892] 08/25/2019 12:14:52 : Starting the injection process... 
[4892] Trying to load 'C:\Users\Jim\Downloads\snoop.3.0.0-alpha0074\net40\ManagedInjector.net40.x86.dll'... 
[4892] System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully 
[4892]    at ManagedInjectorLauncher.Injector.InjectSnoop(ProcessWrapper processWrapper, String transportDataString) in C:\projects\snoopwpf\ManagedInjectorLauncher\Injector.cs:line 249 
[4892]    at ManagedInjectorLauncher.Injector.InjectIntoProcess(ProcessWrapper processWrapper, InjectorData injectorData) in C:\projects\snoopwpf\ManagedInjectorLauncher\Injector.cs:line 70 
[4892]    at ManagedInjectorLauncher.Program.Main(String[] args) in C:\projects\snoopwpf\ManagedInjectorLauncher\Program.cs:line 45

**Comment by batzen** [comment]
That's strange but exactly what i need. Will try to have a look at this issue next week.

**Comment by batzen** [comment]
Fixed the issue. I forgot to adjust the paths for the build artifacts after changing the compile paths, so some files were missing or in the wrong folder.
Could you try it with https://ci.appveyor.com/api/buildjobs/kf6lbv2cwpfmp4qu/artifacts/output%2Fsnoop.3.0.0-alpha0077.zip again?

**Comment by batzen** [comment]
The file should be in both folders.
Will have a look and come back when i finally fixed it.

**Comment by batzen** [comment]
Forgot to come back here.
Should be fixed now.
Could you try it with https://ci.appveyor.com/api/buildjobs/qvm9k6hts8q5mhg6/artifacts/output%2Fsnoop.3.0.0-alpha0080.zip again?

**Comment by jimfoye** [comment]
Works now, thanks.
