### ISSUE TITLE
Value Input did not support NewLine (\r\n)

### ISSUE THREAD

**Issue by raytangRT** [snoopwpf/snoopwpf#139]
Hi, 

I am trying to enter a new line character in the value field, but the output just showing `\r\n`, expected to produce a new line in the UI.

Can you help to investigate the issue? Thanks.

![image](https://user-images.githubusercontent.com/30689714/64660139-918f6e80-d471-11e9-87b1-dab257314a8c.png)

**Comment by batzen** [comment]
The current value editor does not support multi line editing.
Because the editor is a simple textbox which is not set to support multiple lines your line breaks are trimmed.
The right way to solve this is for snoop to support multi line editing by offering a "..." button in the value editor.

**Comment by batzen** [comment]
Multiline text can now be edited by the new detail value editor.
Just hit the button with "..." in front of the text value.
