### ISSUE TITLE
CTRL_SHIFT stops working

### ISSUE THREAD

**Issue by tetsushmz** [snoopwpf/snoopwpf#140]
Hi,

I have just updated to the latest version of Snoop from the previous one. I've been working with it for about half year without any issues. I built the latest version with VS2019 and ran it. And I found that CTRL_SHIFT key did not always work. I tested the key-mouse combination over various WPF UI elements. Maybe one out of ten works. Even if an element works one time, it fails next time. So, the behavior is flaky.

**Comment by batzen** [comment]
What do you mean with "latest"? The master or develop branch? Does it happen with every application or just one specific application?

**Comment by tetsushmz** [comment]
The master branch. I also downloaded the msi (V2.11.0) and tested it. It behaves the same way. V2.10.0 worked just fine.
I tested it against my app and Visual Studio, which is a WPF app. Sometimes it works fine. Other times, it doesn't. It looks like that the probability of not working is higher when I did NOT click the target app's window after clicking Snoop's snoop button targeted for it. Having a focus or not on the target WPF window before hitting CTRL_SHIFT seems to have something to do with it.

**Comment by batzen** [comment]
Do you remember that 2.10 worked fine or did you test it? I am asking because recent .NET updates even broke window resizing on quite some machines and i don't remember changing something in that area.

**Comment by batzen** [comment]
@tetsushmz Any news?

**Comment by tetsushmz** [comment]
So, here's my conclusion so far. Snoop, regardless of its version and Windows 10 version, does not always respond to CTRL_SHIFT key combination.

I got another PC (running Windows 10 V1803, so it's kind of old), installed the latest Visual Studio 2019 (as a target WPF app) and Snoop V2.8.0 (very old) on it. I tested if Snoop can detect the UI elements on the first window of Visual Studio (devenv.exe) after the splash screen. Snoop sometimes responds to CTRL_SHIFT, but doesn't other times, on even the same UI elements. It behaves flaky, just like V2.11.0 does.

I'm mostly using FlauInspect to detect XPath in automating UI testing WPF apps. Sometimes, I needed to use Snoop to detect foreground colors of TextBlocks, for example. I thought Snoop worked fine, but I'm afraid I was wrong. FlauInspect, on the other hand, detects everything on that first Visual Studio window without any issue by holding the CTRL key on a UI element. It says everything on that window is a WPF element.

**Comment by batzen** [comment]
Could you re-test this with the latest CI-build of snoop?
I made a change to the code that runs when CTRL + Shift is pressed.

You can grab the latest build from https://ci.appveyor.com/project/batzen/snoopwpf/branch/develop/artifacts

**Comment by tetsushmz** [comment]
I installed v3.0.0-alpha0116 msi and snooped Visual Studio 2019's first wizard page. I don't think I'm seeing any better behavior, though. Sometimes CTRL_SHIFT works, other times doesn't on the same UI element.

**Comment by batzen** [comment]
That's not the latest build from appveyor.
The versions from appveyor have a lower version number. Somehow gitversion reset the version to 1 after i tagged the current alpha release.
Could you test with the version from https://ci.appveyor.com/project/batzen/snoopwpf/branch/develop/artifacts ?

**Comment by tetsushmz** [comment]
OK. I installed 3.0.0-alpha0048.msi from the AppVeyor site. Is it the latest build? The one on GitHub is alpha 0116 and seems to be higher than 0048.
Anyhow, the behavior is the same. No differences.

**Comment by batzen** [comment]
The version number is produced by gitversion and think i made a mistake while creating a tag. That's why the latest build has a lower version number.

Will investigate your issue further then.

**Comment by batzen** [comment]
I just tested the launcher of VS 2019 and i can snoop with CTRL + Shift without any problems.
Any chance you could debug the issue on your machine @tetsushmz?
The code responsible for that is located in `SnoopUI.xaml.cs` and then inside `HandlePreProcessInput`.

**Comment by tetsushmz** [comment]
I downloaded 3.0.0-alpha0080.msi and ran it against VS2019 launcher. The issue is still there. I think I was able to come up with a repro step that at least works 100% on my computer.

1. Start Snoop.
2. Start VS2019.
3. Snoop it.
4. Click a white area on the VS2019 wizard page just to get the focus back on the window.
5. CTRL_SHIFT over the white area just under the icon inside the "Close or check out code" button on the left side of the wizard.
6. Snoop encloses the whole button with the red border.
7. CTRL_SHIFT on the word "from" in the "Get code from an online repository like GitHub or Azure DevOps".
8. Snoop encloses the whole string in red.
9. CTRL_SHIFT on the word "check" in the "Clone or check out code".
10. Snoop does not react to it for some reason, though I can accept it because the behavior is consistent.
11. Repeat steps 5, 6, and 7.
12. Now, step 8 does not happen.

**Comment by batzen** [comment]
Ok, now i can reproduce your issue. Nice.
Will try to find a solution.

**Comment by batzen** [comment]
And fixed ;-)

**Comment by tetsushmz** [comment]
I tested 0084. It works much better. Thanks for the fix. Have happy holidays!
