### ISSUE TITLE
Add support for showing behaviors

### ISSUE THREAD

**Issue by batzen** [snoopwpf/snoopwpf#144]
Snoop should be able to list attached behaviors.

**Comment by dezsiszabi** [comment]
Hi,

Just to clarify: do you mean support for showing the applied behaviors (`Microsoft.Xaml.Behaviors.Behavior` and `System.Windows.Interactivity.Behavior`) on the selected element?

If yes, I worked on this a bit today and have something like this going:

![image](https://user-images.githubusercontent.com/6433293/67151969-451f2600-f29c-11e9-8e54-65df2f732fdb.png)

New tab named `Behaviors`.
Two rows separated by a grid splitter.
Top part has a listbox showing the behaviors of the attached element.
Bottom part reuses the property inspector control and shows properties of the selected behavior.

Is this what you're after? If not, can you clarify and maybe provide some "requirements" on what exactly you'd expect to be implemented?

**Comment by batzen** [comment]
I had no real plan or requirements in mind yet.
Your solution looks nice.
Could you create a PR targeting the develop branch?
If you'd like you can add your twitter name (if you have one), so i can tweet about your addition once it's merged.
As i am unavailable from 23th october till 14th november i can have a look at your PR afterwards.

**Comment by dezsiszabi** [comment]
I opened #149 
Let me know if there are any changes required. And I'm expecting them as I didn't spend that much time on the whole thing. Just created the PR so you can try it out and give feedback.

**Comment by batzen** [comment]
Added in #149 
Thanks a lot @dezsiszabi
