### ISSUE TITLE
Format and parse property values with the same format provider

### ISSUE THREAD

**Issue by gix** [snoopwpf/snoopwpf#150]
Property values are displayed in a different style than they are parsed when entered. Presumably formatting is done using an invariant (or English) culture, and parsing with the user-specific culture.

For example, if Windows is running with some European region setting with `,` as decimal separator, a margin property value is formatted as `4,20,5,2`, but when changing this value I have to replace all delimiters and write `4;20;5;2`.

**Comment by batzen** [comment]
That also bugs me for years now, but i started using spaces as separators to work around this. Will have a look sometime in November.
