### ISSUE TITLE
Dependency properties are filtered wrong and less properties are shown than should be

### ISSUE THREAD

**Issue by swiix** [snoopwpf/snoopwpf#151]
AutomationProperties Class support is available, KeyboardNavigation not
please add this :)

Thank you for snoop, I love it

**Comment by batzen** [comment]
It's not an issue that's limited to KeyboardNavigation properties, but many more.
That was caused by a wrong type check when getting dependency properties for objects.
I will re-title the issue to make that clear.

**Comment by batzen** [comment]
As the bug is now fixed i will have to add a new option/switch to disable showing properties from uncommon types, because those uncommon properties cause a lot of noise.

**Comment by batzen** [comment]
Added a switch in the ui to show uncommon properties.
