### ISSUE TITLE
Feature Request. Path from one element to another

### ISSUE THREAD

**Issue by JazzMario** [snoopwpf/snoopwpf#153]
We are writing automated tests for WPF application and using XAML path. Some times we need to write long XamlPath from one element to another and it takes long time. Could you please add possibility to get such path automatically?

**Comment by batzen** [comment]
You mean something like a context menu in the left hand tree which contains an option to copy the path?
How would such a path look like? Do you have some examples?
Which identifier is used in those paths? The Uid? The name? The AutomationName?

**Comment by batzen** [comment]
@JazzMario ping

**Comment by batzen** [comment]
@JazzMario ping
