### ISSUE TITLE
配额不足，无法处理此命令。

### ISSUE THREAD

**Issue by wanglehui** [snoopwpf/snoopwpf#154]
**Place your issue description here.**

Exception details:
System.ComponentModel.Win32Exception (0x80004005): 配额不足，无法处理此命令。
   在 MS.Win32.UnsafeNativeMethods.PostMessage(HandleRef hwnd, WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   在 System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
### Environment
- Snoop 2.11.0.0
- Windows 6.3.17763
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
I'd need a few more details for this.
What did you do before this error happened?
