### ISSUE TITLE
Could not find the injector launcher.Snoop requires this component, which is part of the snoop project, to do it's job.If you compiled snoop you should compile all required components.If you downloaded snoop you should not omit any files contained in the archive you downloaded.

### ISSUE THREAD

**Issue by chenhaha2016** [snoopwpf/snoopwpf#155]
**Place your issue description here.**

Exception details:
System.IO.FileNotFoundException: Could not find the injector launcher.
Snoop requires this component, which is part of the snoop project, to do it's job.
If you compiled snoop you should compile all required components.
If you downloaded snoop you should not omit any files contained in the archive you downloaded.
文件名:“E:\snoopwpf\Build\Debug\ManagedInjectorLauncher32-4.0.exe”
   在 Snoop.Injector.Launch(WindowInfo windowInfo, Assembly assembly, String className, String methodName, String settingsFile) 位置 E:\snoopwpf\Snoop\Injector.cs:行号 44
   在 Snoop.WindowInfo.Magnify() 位置 E:\snoopwpf\Snoop\WindowInfo.cs:行号 221

---
### Environment
- Snoop 2.11.0.0
- Windows 6.3.17763
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
Did you compile all parts of the Snoop.sln solution?

**Comment by DevDrake** [comment]
Got the same problem with downloaded alpha version. It appears that x86 injector .exe is missing

**Comment by batzen** [comment]
Damn. Will fix it during the weekend and publish a new alpha. That's what happens when all the apps you, in this case I, use are x64...

**Comment by batzen** [comment]
I had a look at this and the zip file contains everything required:
![image](https://user-images.githubusercontent.com/1971030/70371479-c32e9f00-18d3-11ea-9357-25361bb0bc5b.png)

Maybe your anti virus deleted the file? I had a report, after publishing the alpha, that some files were falsely marked as a virus. I even contacted some major anti virus vendors and reported the false positives to them.
But it guess i will have to add some kind of integrity check to snoop when it starts and report any files missing during that check.
