### ISSUE TITLE
Could not find the injector launcher.Snoop requires this component, which is part of the snoop project, to do it's job.If you compiled snoop you should compile all required components.If you downloaded snoop you should not omit any files contained in the archive you downloaded.

### ISSUE THREAD

**Issue by cosisoft** [snoopwpf/snoopwpf#163]
**Place your issue description here.**

Exception details:
System.IO.FileNotFoundException: Could not find the injector launcher.
Snoop requires this component, which is part of the snoop project, to do it's job.
If you compiled snoop you should compile all required components.
If you downloaded snoop you should not omit any files contained in the archive you downloaded.
文件名:“C:\Users\zhanglq\AppData\Roaming\Microsoft\Installer\{C6A9EE2E-6A31-4E14-A61E-11F41F9F12C3}\ManagedInjectorLauncher64-4.0.exe”
   在 Snoop.Injector.Launch(WindowInfo windowInfo, Assembly assembly, String className, String methodName, String settingsFile)
   在 Snoop.WindowInfo.Snoop()

---
### Environment
- Snoop 2.11.0.0
- Windows 6.1.7601
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
How did you install snoop?
