### ISSUE TITLE
Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by mmahfoudh01** [snoopwpf/snoopwpf#168]
**Place your issue description here.**

Exception details:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Snoop.Shell.EmbeddedShellView..ctor()
   at Snoop.SnoopUI.InitShell()
   at Snoop.SnoopUI..ctor()
   at Snoop.SnoopUI.SnoopApplication()
   at Snoop.SnoopUI.GoBabyGoForCurrentAppDomain(String settingsFile)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

---
### Environment
- Snoop 2.11.0.0
- Windows 6.1.7601
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
Which powershell version do you have installed on the machine where you get that error? The minimum required version is 3.0.

**Comment by mmahfoudh01** [comment]
Thank You, installing ps new version has solved it.

**Comment by batzen** [comment]
The next version of snoop will hide the tab if the correct version is not installed 😉
