### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by pe-david** [snoopwpf/snoopwpf#169]
**Place your issue description here.**

Exception details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
### Environment
- Snoop 3.0.0.0
- Windows 6.3.16299
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
Hi there,
that's sadly not enough information to investigate.
What did you do while that error happened?
Were there any InnerExceptions?
Are you able to reproduce the issue?
Could you provide a repro?

**Comment by pe-david** [comment]
Sadly… I don’t really have any more. Focused on other things at the time. Closed the Snoop window. Closed the Snoop app. Tried to close Snoop in the Task Manager, but did not find it. Tried to search for text in VS 2019 and your exception dialog kept up, even though I stopped debugging. Could not search until I restarted Visual Studio. Then all seemed ok, but I have not run Snoop since.

**Comment by batzen** [comment]
Will close this issue then. If you encounter such error again feel free to open a new issue.
