### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by xiangsxuan** [snoopwpf/snoopwpf#171]
Problem description:
I was snoopping the VisualStudio and Frequently switching screen resolution , when I try to close snoop, However, it occurs an Exception with an error Window. Every time when I try to close the error window, it will create an new error window with the same following Exception details.

Exception details:
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---
### Environment
- Snoop 3.0.0.0
- Windows 6.3.18363
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
Sadly that's not enough information to do anything.
What do you mean with "frequently switching screen resolution"?

**Comment by batzen** [comment]
@xiangsxuan ping
