### ISSUE TITLE
Using snoop approach for other needs (how to debug)

### ISSUE THREAD

**Issue by banchmax** [snoopwpf/snoopwpf#191]
Hi guys, first of all - snoop is really useful application, I solved many issues in my practice only because of this app exists! Thank you for your time! Now I'd like to ask, I'm going to use snoop code base for the lighter version of the application, so the only thing I need is : 

- user drags targed to wpf app;
- he/she clicks on UI control and then if the particular control (say textbox) has specific attached property then new dialog appears;
- where user can read property value;

So that I don't need to have visual tree traversing and sophisticated property grid that shows all the properties,  datacontext and either triggers... 

I dowloaded source code, and I was able to build. Now I see it in details. As I understand you have launcher which executes command line command, which calls core code. So that if I run application from within visual studio I can't debug core code. In other words if I place break point into Snoop.Windows.SnoopUI constructor then vs can't hit this break point, and it's understandable becuase you upload core assembly on the fly, and debugger is not attached to the code. 

Probably it's possible to manually attach debugger of other instance of visual studio or even the same instance to the snoop window (with visual tree) once it is shown, but it doesn't sound convenient and right. 

How do you guys debug your application. Please share. Thank you!

**Comment by batzen** [comment]
Hi,

If you want to debug the injector launcher, and the injection code, you can pass your target process id and "-debug" via commandline to it. That will trigger Debugger.Launch.
If you want to debug Snoop.Core you can attach a debugger to your target process, open SnoopManager.cs in that debugger instance and set breakpoints there. 

Hope that helps.

**Comment by banchmax** [comment]
Thank you for the answer, I just thought maybe there is another way so that I don't need to do not attach debugger manually... 

Say if I always know what application I want to connect then to then I probably don't need to use launcher at all. Could anybody tell me how to eliminate launcher, and attach snoop to the application by name. 

Thanks!

**Comment by batzen** [comment]
There is currently now commandline option to attach by process name. It's currently only possible to attach by process id, which should work fine in your case if i understood your use case correctly.

**Comment by banchmax** [comment]
Let's say I know either name or process id, can I eliminate launcher, so that when I press F5, I will see right away form with tree view and property grid, and it will be attached to debugger automatically by VS?

**Comment by batzen** [comment]
I still might not fully understand your issue.
To clarify:
If you want to debug the tree view and property grid from snoop (or any code inside `SnoopManager.cs`) you have to debug your own application as the tree view and property grid will run inside your application process.

If you want to debug the injection process you can start the injector launcher with "-d" as a commandline argument.

If you want to directly attach snoop to a certain process without having to drag the crosshair etc. you have to start `Snoop.InjectorLauncher.x64.exe` or `Snoop.InjectorLauncher.x86.exe` and provide the target process id as a commandline argument to it.
A sample commandline would be `Snoop.InjectorLauncher.x64.exe -t YOUR_PROCESS_ID`.
It does not matter much if you use the x64 or x86 version of the launcher as it will automatically fix any architecture mismatch and redirect to the correct launcher. It's just a bit slower if you start the "wrong" launcher.

Please note that snoop consists of:
- snoop.exe which shows the ui to select some application
- Snoop.InjectorLauncher which gets launched by snoop.exe, or by you directly, to inject snoop into any target application
- Snoop.GenericInjector which gets injected into the target application by Snoop.InjectorLauncher and is responsible for aquiring handles to the .NET runtime
- Snoop.Core which gets loaded by Snoop.GenericInjector and contains the diagnostics ui (tree view, propertygrid etc.) you see as the final result

**Comment by banchmax** [comment]
Thank you for such a detailed answer! I think I was not clear, let me paraphrase it: 

I'm looking for a way to disable launcher at all and show snoop.core directly.  Right now, as you mentioned too, I have to drag&drop target to the wpf based application, after that as I understand launcher contains a code that links snoop.core and the selected application, so that snoop.core is able to reconstruct visual tree and to show the property grid with specific properties of the selected in the tree ui element. (in my pervious response 'tree' and 'property grid' referred to the visual tree and property grid which is used to show properties of the selected ui element from that tree -  as we can see it on main view of snoop.core)

In my case I know the application that I want to investigate and that's why I don't need to drag&drop target onto some wpf application. So my question is - can I run snoop.core without launcher, because if it's possible, then snoop.core will be attached to debugger automatically as I can expect.

Thank you!

**Comment by batzen** [comment]
@banchmax Sorry for my late response.

If you want to completely get rid of the launcher process you have to reference Snoop.Core in your application, but this is not officially supported, i strongly suggest not doing that, and will currently prevent everyone else from attaching Snoop to your process.

If you only want to get rid of the drag&drop part you can just invoke snoop.exe.
The commandline for snoop.exe would be `snoop.exe inspect --targetPID yourProcessId`.

Invoking the injectorlauncher via commandline is not as easy as i described in my previous comment as it would also require a assemblyname, classname, methodname and the target process id.
