### ISSUE TITLE
Support for custom events

### ISSUE THREAD

**Issue by ramondeklein** [snoopwpf/snoopwpf#197]
I have a WPF application and implemented some custom events. I would like to be able to track these events, but I can only select the common events. I can imagine it's impossible for Snoop to determine the custom events, but it would be great if we can specify it by name.

**Comment by batzen** [comment]
I theory this should already work and it does at least work for things like MahApps.Metro.
Could you provide a repro where you define custom routed events that are not picked up by snoop?

In fact it's pretty easy for snoop to get all registered events by invoking `EventManager.GetRoutedEvents`.

**Comment by ramondeklein** [comment]
@batzen Maybe Snoop can trace them, but I cannot select the events in this window. Maybe I am missing something?
![image](https://user-images.githubusercontent.com/6048186/103092392-5d54a880-45f7-11eb-9f07-d24738416f26.png)

**Comment by batzen** [comment]
The events from MahApps.Metro are displayed in that section. That's why i asked for a repro. 😉

**Comment by batzen** [comment]
Just to be sure we are talking about the same.
You mean custom routed events or regular events?

**Comment by ramondeklein** [comment]
I was confused by the header "common events", so I didn't notice that my own class was listed in this view (shame on me). Now I carefully scanned the list and it's in there. Thanks for a great tool. It's way more capable compared to VS built-in tools.

Snoop 🥇

**Comment by batzen** [comment]
Will change the header to "Tracked events" that makes much more sense. ;-)
