### ISSUE TITLE
Add a warning to zoomer if target has `TextOptions.TextFormattingMode=Display`

### ISSUE THREAD

**Issue by xwg1984** [snoopwpf/snoopwpf#219]
![图片](https://user-images.githubusercontent.com/1962741/104560213-85787a00-5680-11eb-939a-5834b6436032.png)

**Comment by batzen** [comment]
That's really strange.
Can reproduce your issue and will have a look.

**Comment by batzen** [comment]
So i did some digging and this is what i found out:
It's strange that the icon is rendered crisp and clear and the text is not.
Zooming further in with snoop causes the text to be rendered crisp and clear after reaching a certain zoom level.
So i had a look at the properties set on the textblock from Visual Studios menu items and compared them to a the properties from another application where the text is always rendered crisp.
Visual Studio sets the `TextOptions.TextFormattingMode` to `Display` on it's window, which is the culprit.
It should be set to `Ideal` instead. If it's set to `Ideal` the text is rendered crisp on all zoom levels in snoop.
`TextOptions.TextFormattingMode=Ideal` is the default for WPF, so i don't know why Visual Studio overwrites this to `Display` in it's default style, at least for `MainWindow` (didn't check other window styles).

What i might do is to add a warning to the zoom control in Snoop which gets triggered if `TextOptions.TextFormattingMode` is `Display` and there is no `ScaleTransform`.
The general rule of thumb i use for `TextOptions.TextFormattingMode` is:
Use `Ideal` if there is no `ScaleTransform`.
Use `Display` if there is a `ScaleTransform` and it's zoom is `!= 1`.
