### ISSUE TITLE
Thickness Editor is flaky due to strange ToString/FromString conversion of .NET

### ISSUE THREAD

**Issue by jongleur1983** [snoopwpf/snoopwpf#233]
Primer:
Tried to resolve it myself, but I get a compiler error ("Executor.obj: [LNK1112] module machine type 'x86' conflicts with target machine type 'ARM'"), so documenting the issue first.

I'd be happy to resolve the issue myself if anyone could help me overcome that problem.

Back to topic:
Using a German operating system, the Thickness type isn't properly converted, as it's ToString() method isn't safe for round tripping.
Let's take the default value (0 0 0 0) as an example.

- working culture invariant roundtripping could be 0 0 0 0 => THICKNESS => 0 0 0 0
- ToString() produces for InvariantCulture 0,0,0,0
- ToString() for German produces 0;0;0;0
- 0;0;0;0 cant' be converted back 

In Screenshots:
- A thickness in Snoops main window, unchanged:
![image](https://user-images.githubusercontent.com/2063360/108768049-7e823880-7557-11eb-839c-4f13971e2f14.png)
- editing: (here padding to top could be improved, but that's not the main issue here.)
![image](https://user-images.githubusercontent.com/2063360/108768220-aec9d700-7557-11eb-9112-c156657591d2.png)
- main issue: there's still the edit value "0,0,0,0" active, so just adding a 1 to "0,0,0,10" is an invalid value and can't be converted back.
- typing the entire value again with spaces works

**Comment by batzen** [comment]
Both issue (conversion and layout) you are mentioning here should have been fixed quite some time ago.
Which version of Snoop are you using?

Regarding compilation:
Are you using Visual Studio to build the solution? I placed a ".vsconfig" file beside the solution which should be recognized by Visual Studio and it should notify you about missing components.
You can also import that file from the Visual Studio installer manually and it should install all the missing components.
In this case you are missing VC++ ARM and VC++ ARM64 build tools.
I forgot to add a hint about that to the readme and will add that immediately.

**Comment by jongleur1983** [comment]
indeed, had to install the current version to see that fixed (sorry for the inconvenience). Nevertheless going to solve the build issue now, maybe I can help somewhere else.

**Comment by jongleur1983** [comment]
still no luck getting the build to work, neither in Rider what I'd prefer nor in Visual Studio.
Maybe I'll try again in the next days.
Closing this issue as it's resolved. 
Thanks!

**Comment by batzen** [comment]
I am also using Rider most of the time. 😉
Have you tried importing the .vsconfig file in the Visual Studio installer?
It's quite important for me that people can easily build the project.

**Comment by jongleur1983** [comment]
solved the build issue by commenting the ARM referencing lines in the GenericInjector project, works for testing on x86 architecture.
