### ISSUE TITLE
invoking wpfsnoop automationId

### ISSUE THREAD

**Issue by AnassKartit** [snoopwpf/snoopwpf#237]
Hi,
Thanks for the great work, I use wpfsnoop to inspect automationId , however when I invoke automationid with tools like test.white I don't seem to find the element does that mean only wpf works since it injects itself? any way to invoke element automation ? Thanks

**Comment by AnassKartit** [comment]
Thanks for your response, I have checked the other tools cannot do this because of the injection property snoop able to do, is it possible to show an example of how to build a proxy for automation using snoop (clicking a button for example by using snoop framework?)

**Comment by batzen** [comment]
You can have a look at `SimpleUIAutomation.Application` and `SimpleUIAutomation` inside the "TestHarnesses" folder of this repository if you want an example on how to use the injection process of snoop to build something like an ui automation tool.

But be warned that it's just a small sample and that building your own ui automation tool requires a lot more work.
