### ISSUE TITLE
Display Scaling

### ISSUE THREAD

**Issue by rrperkin** [snoopwpf/snoopwpf#252]
Snoop on my 4K display within an RDP full screen session, which is scaled 175%, looks extremely tiny. Would like some kind of "large" mode that doubles height and width of the control bar. See the attached image for relative sizes.

![image](https://user-images.githubusercontent.com/466101/118308749-2d704980-b4a1-11eb-8011-86cbb33ee13d.png)

**Comment by batzen** [comment]
Which version are you using? Could you try the preview version from the CI build?

**Comment by rrperkin** [comment]
3.01 stable, I think. I pulled the MSI from the GitHub source.

Rob

**Comment by batzen** [comment]
Could you try the version from https://ci.appveyor.com/project/batzen/snoopwpf/branch/develop/artifacts ?

**Comment by rrperkin** [comment]
Yes. It was easy to install. The behavior is the same. 

More Info: The environment is a Hyper-V virtual machine, running locally on the computer with three 4K displays side-by-side. 

On the host, Snoop picks up the display scaling, apparently from Monitor 1, and looks large enough. If the other monitors are using different scaling, it retains the scaling computed from Monitor 1 when the control bar is dragged to those monitors. So, 100% on monitor 1, 175% on 2 and 3, the Snoop bar is unreadably small for my middle-aged eyes no matter where I drag it. 175% on monitor 1, and the bar is 175% larger, retaining its size regardless of scaling settings on 2 and 3.

In the guest VM, over RDP, Visual Studio and other applications pick up the scaling, Snoop does not. But, configuring a compatibility setting for “all users”, “High DPI scaling override”, with the checkbox checked and the setting set to “System” scales Snoop so that it’s larger, and exhibits the pixel-blurring behavior sometimes found HDPI-unaware apps. Other compatibility settings produce fragmented UI elements and refresh inconsistencies that make the program unusable. 

So far I’ve only looked at the bar; the other UI elements don't seem too small to me. This suggests that a manifest setting might correct the problem, but I'm not super-sure about that idea. 

![image](https://user-images.githubusercontent.com/466101/118334467-82708780-b4c2-11eb-9a98-02462aa95e48.png)

**Comment by batzen** [comment]
Could you give it another try using the version from https://ci.appveyor.com/project/batzen/snoopwpf/branch/develop/artifacts ?

**Comment by rrperkin** [comment]
It looks fixed with that build. Thanks for giving this your attention.

**Comment by batzen** [comment]
Thanks for bringing this to my attention. Don't hesitate to create issues here if you find something broken or missing in Snoop.
