### ISSUE TITLE
Exception at SnoopMainBaseWindow.FindRoot() with background dispatcher hosted visual 

### ISSUE THREAD

**Issue by evgeny-burmakov** [snoopwpf/snoopwpf#254]
There is exception on accessing to presentationSource.RootVisual when PresentationSource is placed at background dispatcher and provides VisualTarget.RootVisual inside PresentationSource.RootVisual accessor.  VisualTartget.RootVisual contains VerifyAccess() which generates exception.

Next changes at  SnoopMainBaseWindow.FindRoot() solve the issue:

```c#
protected virtual object? FindRoot()
{
	object? foundRoot = null;

	if (SnoopModes.MultipleDispatcherMode)
	{
		foreach (PresentationSource? presentationSource in PresentationSource.CurrentSources)
		{
			if (presentationSource is null)
			{
				continue;
			}

			if (presentationSource.Dispatcher.CheckAccess()
				&& presentationSource.RootVisual is UIElement element
				&& element.Dispatcher.CheckAccess())
			{
				foundRoot = presentationSource.RootVisual;
				break;
			}
		}
	}
	...
}
```

**Comment by batzen** [comment]
Could you provide a repro for that?
I will have to change a few other places too to fully support this scenario, so it would be nice to have a small application where i can test my changes.

**Comment by evgeny-burmakov** [comment]
Thanks for quick fix.
There is an example for verifying if any another places might be affected:
[WpfApp.zip](https://github.com/snoopwpf/snoopwpf/files/6520810/WpfApp.zip)
