### ISSUE TITLE
Out of memory exception in snoop after target app was converted from .NET 4.8 to .NET 5

### ISSUE THREAD

**Issue by spacestr** [snoopwpf/snoopwpf#266]
07/02/2021 07:00:52: Starting the injection process...
07/02/2021 07:00:52: Trying to load "C:\Program Files (x86)\Snoop\Snoop.GenericInjector.x86.dll"...
07/02/2021 07:00:52: Trying to allocate 217 bytes in foreign process...
07/02/2021 07:00:52: Successfully allocated memory in foreign process.
07/02/2021 07:00:53: Trying to load "C:\Program Files (x86)\Snoop\Snoop.GenericInjector.x86.dll" in process "29056"...
07/02/2021 07:00:53: Trying to write 116 bytes in foreign process
07/02/2021 07:01:01: Successfully loaded "C:\Program Files (x86)\Snoop\Snoop.GenericInjector.x86.dll" with handle "481492992" ("481492992") in process "29056".
07/02/2021 07:01:01: Calling "ExecuteInDefaultAppDomain" on injector component...
07/02/2021 07:01:01: Args = net5.0-windows<|>C:\Program Files (x86)\Snoop\net5.0-windows\Snoop.Core.dll<|>Snoop.Infrastructure.SnoopManager<|>StartSnoop<|>C:\Users\---\AppData\Local\Temp\tmpAC09.tmp<|>C:\Users\---\AppData\Local\Temp\tmpAF06.tmp
07/02/2021 07:03:42: Received "-1" from injector component.
07/02/2021 07:03:42: ##############################################
07/02/2021 07:03:42: Log from injector component:
07/02/2021 07:03:42: ##############################################
07/02/2021 07:03:42: net5.0-windows<|>C:\Program Files (x86)\Snoop\net5.0-windows\Snoop.Core.dll<|>Snoop.Infrastructure.SnoopManager<|>StartSnoop<|>C:\Users\---\AppData\Local\Temp\tmpAC09.tmp<|>C:\Users\---\AppData\Local\Temp\tmpAF06.tmp
Trying to get executor for framework 'net5.0-windows'...
NetCoreApp3_0Executor: Getting handle for coreclr.dll...
NetCoreApp3_0Executor: Got handle for coreclr.dll.
NetCoreApp3_0Executor: Getting handle for GetCLRRuntimeHost...
NetCoreApp3_0Executor: Got handle for GetCLRRuntimeHost.
NetCoreApp3_0Executor: Trying to get runtime host...
NetCoreApp3_0Executor: Got runtime host.
NetCoreApp3_0Executor: Trying to run ExecuteInDefaultAppDomain...

07/02/2021 07:03:42: ##############################################
07/02/2021 07:03:42: Trying to free module "Snoop.GenericInjector.x86.dll" with handle 481492992 in process "29056"...
07/02/2021 07:03:42: Freeing "481492992" in process "29056"...
07/02/2021 07:03:42: Could not create remote thread.
07/02/2021 07:03:42: Failed to inject Snoop into process Application (PID = 29056)
07/02/2021 07:03:42: System.Runtime.InteropServices.COMException (0xFFFFFFFF): Exception from HRESULT: 0xFFFFFFFF
   at Snoop.InjectorLauncher.Injector.InjectSnoop(ProcessWrapper processWrapper, InjectorData injectorData) in C:\projects\snoopwpf\Snoop.InjectorLauncher\Injector.cs:line 319
   at Snoop.InjectorLauncher.Program.Run(InjectorLauncherCommandLineOptions commandLineOptions) in C:\projects\snoopwpf\Snoop.InjectorLauncher\Program.cs:line 106
![image](https://user-images.githubusercontent.com/58531412/124288419-024fc100-db06-11eb-8fcf-5433462b5fad.png)

The inspected application then crashes with this error:
'System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:(no path); DataItem=null; target element is 'ExportOptions' (HashCode=2859471); target property is 'TreeItem' (type 'TreeItem')System.Windows.Data Information: 20 : BindingExpression cannot retrieve value due to missing information. BindingExpression:Path=ErrorInfo.Description; DataItem=null; target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String')'

The inspected application runs stable otherwise.

**Comment by batzen** [comment]
Any chance you can share your application?

How much RAM does the application consume before trying to attach Snoop?

**Comment by spacestr** [comment]
I cannot share the application unfortunately, it is very large and proprietary.
It uses 770 MB of RAM when idle and I try to attach.

**Comment by batzen** [comment]
That's strange. Snoop should allocate some memory, but not ~1.3 GB to hit the 2 GB limit of a 32 bit application.
Could you provide a memory dump?
Or could you run a tool like DotMemory while attaching to the process and share the results?

**Comment by spacestr** [comment]
While attaching, the memory use grew to 1064MB and then the above error displayed followed by this one.
![image](https://user-images.githubusercontent.com/58531412/124308551-48188380-db1e-11eb-838b-12064216cbbb.png)

The memory drops back to the original as soon as the error shows, so I don't have enough time to capture snapshots.

**Comment by spacestr** [comment]
One extra data point:
Back when the application was on .NET Framework 4.8, I was using Snoop v2 and it worked perfectly.

**Comment by batzen** [comment]
Ah, judging from the screenshot it looks like you are you merged resource dictionaries at deeply nested levels. In that case in a popup. If you are doing that often it might explain the enormous amounts of memory allocates.
Visualization of popup and resource dictionaries was added in some 3.x version.
Can you verify that?
If that's really the case you might want to change that in your application as it might cause performance issues in your application.
If it's something you can't change i could add some mitigations for such cases to Snoop.

**Comment by spacestr** [comment]
My application contains hundreds of screens each with various controls,
popups, etc.
To improve performance I preload all the screens and only toggle
visibility, and have a single shared resource dictionary which contains all
other resource dictionaries.
Unfortunately this was the best solution I could find.. prioritize
operational performance instead of startup time and memory use.

**Comment by batzen** [comment]
That's totally fine, but it really looks like you are including some large resource dictionaries at the level of a popup. Maybe by accident.

I will change some things in Snoop to prevent it from consuming so much memory. Maybe it wasn't a good idea to add every resource entry as a tree node and not taking multiple inclusions of resource dictionaries into account. 😉

**Comment by spacestr** [comment]
Thank you!

It may indeed be strange to include such a massive dictionary in a popup,
but it's by reference to a static dictionary since it contains all the
font/color/style definitions already.

**Comment by batzen** [comment]
Should be fixed with 4f5ce83aca9105412bdd95fd4479e344190e2b0b 
Could you try the latest CI build version from https://ci.appveyor.com/project/batzen/snoopwpf/build/artifacts?

**Comment by spacestr** [comment]
Since you are working on this during the weekend I went to try it out at work as well.

On first attempt, after 1 minute the tree view appeared, but shortly after I got 3 blank "Snoop error" windows and everything vanished.
On 2nd try I got this:
![image](https://user-images.githubusercontent.com/58531412/124361091-1e289500-dbe2-11eb-9965-dda6adcfd7f3.png)
![image](https://user-images.githubusercontent.com/58531412/124361096-284a9380-dbe2-11eb-8bce-34c46fedc3c3.png)

**Comment by batzen** [comment]
Could you try to open the Snoop settings (before attaching), uncheck "EnableDiagnostics" and try to attach again?
ResourceDictionary nodes shouldn't be the problem anymore, but as i added diagnostics features to Snoop in version 3.1 this might cause memory issues in your case now.

**Comment by spacestr** [comment]
I got the same exact error, but this time within a few seconds of attaching
instead of over a minute.

**Comment by batzen** [comment]
That's at least a performance improvement...
I still don't understand why just accessing the resource dictionaries causes so much memory to be allocated.
Except there is some kind of circular reference on the dictionaries.

I just added some tracing to get a few more details.
Could you try the latest CI build again and run "dbgview" while trying to attach?
"dbgview" should then show some lines you'd have to post here. A screenshot of those lines would also work, of course.

**Comment by spacestr** [comment]
It didn't crash this time, but I think it was just about to..
[DbgView.LOG](https://github.com/snoopwpf/snoopwpf/files/6759036/DbgView.LOG)

I then went to inspect 3 elements. First 2 got found with some delay, then the 3rd made the application vanish. It's appended in this log copy:
[DbgView2.LOG](https://github.com/snoopwpf/snoopwpf/files/6759039/DbgView2.LOG)

**Comment by batzen** [comment]
Ok. Snoop is trying to visualize > 135 000 resource dictionaries in your first log and > 220 000 in the second log.
That's way too much for the current implementation.

I now made all nodes for `ResourceDictionary` lazy loaded.
Could you give it another try to see if the crashes are gone?

**Comment by spacestr** [comment]
It's fixed!
Great work! Crazy fast turn around time.. only 2 days! Thank you so much!!!

**Comment by batzen** [comment]
Glad i could help.

Well the turn around time highly depends on how much spare time i can allocate to OSS, how much info i got to find the root cause and how complex the issue is.
