### ISSUE TITLE
Could not find the injector launcher "D:\snoopwpf\bin\Debug\Snoop.InjectorLauncher.x64.exe".Snoop requires this component, which is part of the Snoop project, to do it's job.- If you compiled snoop yourself, you should compile all required components.- If you downloaded snoop you should not omit any files contained in the archive you downloaded and make sure that no anti virus deleted the file.

### ISSUE THREAD

**Issue by hongjiapeng** [snoopwpf/snoopwpf#275]
**Place your issue description here.**

Exception details:
System.IO.FileNotFoundException: Could not find the injector launcher "D:\snoopwpf\bin\Debug\Snoop.InjectorLauncher.x64.exe".
Snoop requires this component, which is part of the Snoop project, to do it's job.
-If you compiled snoop yourself, you should compile all required components.
-If you downloaded snoop you should not omit any files contained in the archive you downloaded and make sure that no anti virus deleted the file.
File name: "D:\snoopwpf\bin\Debug\Snoop.InjectorLauncher.x64.exe"
   In Snoop.InjectorLauncherManager.Launch(ProcessInfo processInfo, IntPtr targetHwnd, String assembly, String className, String methodName, String transientSettingsFile) position D:\snoopwpf\Snoop\InjectorLauncherManager.cs: line number 51
   In Snoop.InjectorLauncherManager.Launch(ProcessInfo processInfo, IntPtr targetHwnd, MethodInfo methodInfo, TransientSettingsData transientSettingsData) position D:\snoopwpf\Snoop\InjectorLauncherManager.cs: line number 24
   In Snoop.ProcessInfo.Magnify(IntPtr targetHwnd) location D:\snoopwpf\Snoop\ProcessInfo.cs: line number 54

---
### Environment
-Snoop 1.0.0.0
-Windows 6.3.22000
-.NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
You have to compile all projects contained in Snoop.sln.

**Comment by hongjiapeng** [comment]
> You have to compile all projects contained in Snoop.sln.

Thank you,it's ok.
