### ISSUE TITLE
Is there any plan for maui ?

### ISSUE THREAD

**Issue by rwecho** [snoopwpf/snoopwpf#276]
thanks

**Comment by rwecho** [comment]
Lots of issues to launch maui app.  WIthout snoopy, I can not locate what's going on. Hope it stable when official release 
thanks for your reply

**Comment by bruno-garcia** [comment]
MAUI has GA'ed, even though there has been some buzz that it's still 'not there yet' it seems that 7.0.200 SDK that's in preview has significant fixes.

I'm personally curious to learn how inspecting on the view structure would look like. 👋

**Comment by ahmed-abdelrazek** [comment]
maui still a #### show but any plans for support?

**Comment by batzen** [comment]
I still don't plan to use MAUI.
If there is no one in the community who's willing to add support for it via a PR, there won't be support for it.
