### ISSUE TITLE
Adorner Layer not visible on certain controls

### ISSUE THREAD

**Issue by DomeAlessi** [snoopwpf/snoopwpf#278]
I remarked that in the recent version of Snoop (among them also the Snoop.3.1.0-rc0324 that I am currently using) the red Adorner layer is not showing around certain controls. In my case doesn't show around some borders or some rectangles, but in the same view other borders are visible.
I remember fiddling with it some week ago because I wanted to hide it cause was preventing me to see the control i was tweaking but since then (I cold be very wrong though ) I am not able to work properly anymore because I have to continuously check the Visual Tree to make sure I am on the good element because the red square is not appearing.

(related but i can make a feature request if necessary)
Would be cool speaking of this to have some checkbox or mini property dialog where the user can set the Adorner Properties, I dunno something like the current Properties panel but dedicated only to the Adorner, in this way you do not need to change the focus on something else to see if you set the margins correctly.

Thank you!

**Comment by DomeAlessi** [comment]
Thank you!
Well unfortunately it occurs in my company app so I do not have the rights to send you some sample. No idea if any memory snapshot or any dump can help though. I can try in my own smaller app but not sure i can repro correctly.

**Comment by DomeAlessi** [comment]
Here's an example of the behavior. I am not sure why it does that and often works on a control type but not the same one in another part of the UI.
![SnoopAdorner](https://user-images.githubusercontent.com/74638638/135699636-fbcde22e-b355-4315-a9d3-16d6ffd481d1.gif)

**Comment by batzen** [comment]
The hang is most likely caused by the new diagnostic feature, as the number of information diagnostics jumps from ~1300 to ~2000 after opening the popup and then from ~2000 to ~2700 after leaving the popup.
Which is quite strange. Maybe there is a bug that causes diagnostics to be added as duplicates, i also notice that it behaves strange sometimes and planned to investigate that.
I guess i should add some kind of export feature for the diagnostics.
Could you share the application you are showing here, or is it the company app you are not able to share?

Regarding the adorner not being visible:
I was not yet able to reproduce that issue and any help in getting a working repro is very appreciated.
Already started to refactor the code responsible for creating/destroying the adorner to improve perf and unify it's usage.
That should also ease the implementation of the adorner options you suggested.

**Comment by DomeAlessi** [comment]
Hello, thanks for the clarification about the hang.
Regarding the application that's the one from the company so unfortunately I won't be able to share any code from there, sorry.
Thanks also for the update on the Adorner I look forward for this feature because in the moment you use Snoop more frequently this can be proven very useful.

As usual sorry for introducing this on another thread but I found a thing that could be quite interesting to discuss for Snoop (and if there is any chance of interest I am willing to cut paste the message below in a dedicated topic :D).

At the moment the Zoomer is used to take a static snapshot of the UI, many times i adjust margins and i need to remove the Adorner but also squint my eyes OR take a screenshot to see if stuff matches. The Zoomer doesn't respond to update changes, which I guess that's not what's intended for but for example I discover this app called PixelZoomer (http://pixelzoomer.com/) that for designing UI is fantastic, the only boring part is that you need to take a screenshot and paste it in, so I came to think that if the Zoomer could have similar features with measuring, zooming and ofc responding to UI changes that would be incredibly effective in designing user contrlols like I am doing these days.
Now I understand that Snoop is not solely made for my usage case but perhaps it's up to you (if you have more insights) to decide if this is a change worth to think about depending on the application userbase.

**Comment by batzen** [comment]
The Zoomer responds to UI updates if you are using the 2D mode.
If it does not you found another bug. ;-)

The Zoomer in 2D mode currently can:
- Respond to UI updates
- Zoom
- Change background color

So missing from your list is measuring which sounds quite interesting.
Could you open another issue for that? We can discuss the other things (responding to updates, zooming there also if they don't work for you).

**Comment by DomeAlessi** [comment]
You are absolutely right, for some reason when I was testing it the other day the image was static (in the floating Zoomer).
I will open a new request for the measuring options.
Thank you!

**Comment by batzen** [comment]
@DomeAlessi Could you download https://github.com/snoopwpf/snoopwpf/suites/3943233970/artifacts/98858121 and check if it works better now?
You can change the highlight options from the tracking options in the menu.
The settings are not yet persisted as i plan to rewrite the settings storage after i released version 3.1.

**Comment by DomeAlessi** [comment]
If i may add something perhaps the default color could be the semi transparent red that was there before so that for user that do not want to fiddle with it nothing changes or that's not more "on the way" than before.

**Comment by batzen** [comment]
That's strange. I will add some tracing and ping you here as soon as i am done.
