### ISSUE TITLE
Improve filter box tooltip

### ISSUE THREAD

**Issue by DomeAlessi** [snoopwpf/snoopwpf#279]
Hello, 

If search for the string "thick" in a Content Presenter the Margin property is shown anyway (currently using Snoop.3.1.0-rc0324).
![image](https://user-images.githubusercontent.com/74638638/134254507-b46b37e9-136a-4708-9cf6-5fa960f4ce68.png)

Not sure what makes it still be there. It still stays if search for "marg" and correctly disappears searching for "marga".

**Comment by batzen** [comment]
That's strange. Will try to reproduce.

**Comment by batzen** [comment]
In fact it's a feature i didn't even know about. 🤦‍♀️
In addition to the property name it matches the name of the property type.
To make this behavior more obvious i will improve the tooltip for the filter box.
