### ISSUE TITLE
InjectorLauncher System.MissingMethodException

### ISSUE THREAD

**Issue by lerrific** [snoopwpf/snoopwpf#280]
The InjectorLauncher fails to inject my dll with this exception:
```
System.MissingMethodException: Attempted to access a missing method.
   at Snoop.InjectorLauncher.Injector.InjectSnoop(ProcessWrapper processWrapper, InjectorData injectorData) in C:\projects\snoopwpf\Snoop.InjectorLauncher\Injector.cs:line 295
   at Snoop.InjectorLauncher.Program.Run(InjectorLauncherCommandLineOptions commandLineOptions) in C:\projects\snoopwpf\Snoop.InjectorLauncher\Program.cs:line 99
```

the arguments i used: 
`Snoop.InjectorLauncher.x64.exe -t 9520 -a "C:\Users\WT\Desktop\inject_test\testdll.dll" -c testdll.Class1 -m Load`

the dll (.net framework):
```
namespace testdll
{
    public class Class1
    {
        public static void Load()
        {
            // todo
        }
    }
}
```

the exe I attempted to inject in to was just a fresh created visual studio 2019 WPF application on the .net framework

Maybe I am just missing something obvious here with the methodName argument? cheers 🙂

**Comment by batzen** [comment]
Hi there.
The method signature has to be `public static int Load(string settingsFile)`, should be non blocking (so the launcher doesn't run till your method ends) and must return 0 on success and something else on failure.

**Comment by lerrific** [comment]
> Hi there. The method signature has to be `public static int Load(string settingsFile)`, should be non blocking (so the launcher doesn't run till your method ends) and must return 0 on success and something else on failure.

Ah, works perfectly now, thanks!
