### ISSUE TITLE
[Feature Request] Be able to import filters or make them available across applications.

### ISSUE THREAD

**Issue by DomeAlessi** [snoopwpf/snoopwpf#283]
Hello,
I create some filters in my test application to be able to see only the properties I debug when I inspect my components.
If i change to another application the filter are not available anymore and I have to redo them.

It would be nice to have a way:

- to import existing filters from one application to the other (something like Save/ Load or clipboard serialization?)

OR

- keep the filters global for all the applications (not sure if there is any side effect but i was thinking that since unsupported properties are already ignored when filtering and WPF user control components are the same maybe this could be another way to access your custom filters).

Edit:
Note: As a workaround I opened **App A** and copied the filters and pasted the list in **App B**, however now I realized that I needed to add an extra property from **App B** so now I need to go to **App A** again and update those filters.
Thank you!

**Comment by batzen** [comment]
Solved by #316
