### ISSUE TITLE
Feature Request: Reattach to latest process

### ISSUE THREAD

**Issue by EgilSandfeld** [snoopwpf/snoopwpf#297]
Title says it, when an attached process closes, Snoop should check every 1 second or so if that process reappears and then reattach when found.

It should be an option to Opt-in to this via Settings, to avoid confusion.

**Comment by batzen** [comment]
In version 4 you could just keep the Snoop launcher running, focus a WPF window and hit CTRL + WIN + ALT + F12 to attach Snoop.

**Comment by batzen** [comment]
@EgilSandfeld I decided to not implement this, as it's already quite easy to attach to a process.
