### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Brehme** [snoopwpf/snoopwpf#307]
Got this exception while snooping my applicaiton. The exception doesn't occure if snoop is not attached. 

Exception details:
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei MS.Internal.AvTrace.AntiFormat(String s)
   bei MS.Internal.AvTraceBuilder.AppendFormat(String message, String arg1, String arg2)
   bei MS.Internal.TraceData.DescribeSourceObject(AvTraceBuilder traceBuilder, Object o)
   bei MS.Internal.TraceData.DescribeTarget(AvTraceBuilder traceBuilder, DependencyObject targetElement, DependencyProperty targetProperty)
   bei MS.Internal.TraceData.Describe(AvTraceBuilder traceBuilder, Object o)
   bei MS.Internal.TraceData.OnTrace(AvTraceBuilder traceBuilder, Object[] parameters, Int32 start)
   bei MS.Internal.AvTrace.Trace(TraceEventType type, Int32 eventId, String message, String[] labels, Object[] parameters)
   bei MS.Internal.TraceData.Trace(TraceEventType type, AvTraceDetails traceDetails, Object p1)
   bei MS.Internal.Data.PropertyPathWorker.ReportNoInfoError(Int32 k, Object parent)
   bei MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)
   bei MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   bei MS.Internal.Data.ClrBindingWorker.AttachDataItem()
   bei System.Windows.Data.BindingExpression.Activate(Object item)
   bei System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   bei System.Windows.Data.BindingExpression.AttachOverride(DependencyObject target, DependencyProperty dp)
   bei System.Windows.Data.BindingExpressionBase.OnAttach(DependencyObject d, DependencyProperty dp)
   bei System.Windows.StyleHelper.GetInstanceValue(UncommonField`1 dataField, DependencyObject container, FrameworkElement feChild, FrameworkContentElement fceChild, Int32 childIndex, DependencyProperty dp, Int32 i, EffectiveValueEntry& entry)
   bei System.Windows.StyleHelper.GetChildValueHelper(UncommonField`1 dataField, ItemStructList`1& valueLookupList, DependencyProperty dp, DependencyObject container, FrameworkObject child, Int32 childIndex, Boolean styleLookup, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)
   bei System.Windows.StyleHelper.GetChildValue(UncommonField`1 dataField, DependencyObject container, Int32 childIndex, FrameworkObject child, DependencyProperty dp, FrugalStructList`1& childRecordFromChildIndex, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)
   bei System.Windows.StyleHelper.GetValueFromStyleOrTemplate(FrameworkObject fo, DependencyProperty dp, EffectiveValueEntry& entry)
   bei System.Windows.StyleHelper.ApplyStyleOrTemplateValue(FrameworkObject fo, DependencyProperty dp)
   bei System.Windows.StyleHelper.InvalidateContainerDependents(DependencyObject container, FrugalStructList`1& exclusionContainerDependents, FrugalStructList`1& oldContainerDependents, FrugalStructList`1& newContainerDependents)
   bei System.Windows.StyleHelper.DoStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle)
   bei System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
   bei System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObje
Exception details truncated at 4000 chars.

---
### Environment
- Snoop 3.0.0.0
- Windows 6.3.19042
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
Can you provide a repro? As the stacktrace only contains framework code it's impossible for me to find out what's causing this error.
The start part of the/untruncated stacktrace might help narrowing the potential cause.

**Comment by Brehme** [comment]
The application is to big to use it as working sample. And I was not able to create a smaller one. 
But I found a binding error in one of the styles:
System.Windows.Data Error: 40 : 
BindingExpression path error: 'BlackColor' property not found on ...

After I fixed that there where no error window in snoop any longer.

For completeness hier is the full stacktrace
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.  
   bei MS.Internal.AvTrace.AntiFormat(String s)  
   bei MS.Internal.AvTraceBuilder.AppendFormat(String message, String arg1, String arg2)  
   bei MS.Internal.TraceData.DescribeSourceObject(AvTraceBuilder traceBuilder, Object o)  
   bei MS.Internal.TraceData.DescribeTarget(AvTraceBuilder traceBuilder, DependencyObject targetElement, DependencyProperty targetProperty)  
   bei MS.Internal.TraceData.Describe(AvTraceBuilder traceBuilder, Object o)  
   bei MS.Internal.TraceData.OnTrace(AvTraceBuilder traceBuilder, Object[] parameters, Int32 start)  
   bei MS.Internal.AvTrace.Trace(TraceEventType type, Int32 eventId, String message, String[] labels, Object[] parameters)  
   bei MS.Internal.TraceData.Trace(TraceEventType type, AvTraceDetails traceDetails, Object p1)  
   bei MS.Internal.Data.PropertyPathWorker.ReportNoInfoError(Int32 k, Object parent)  
   bei MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)  
   bei MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)  
   bei MS.Internal.Data.ClrBindingWorker.AttachDataItem()  
   bei System.Windows.Data.BindingExpression.Activate(Object item)  
   bei System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)  
   bei System.Windows.Data.BindingExpression.AttachOverride(DependencyObject target, DependencyProperty dp)  
   bei System.Windows.Data.BindingExpressionBase.OnAttach(DependencyObject d, DependencyProperty dp)  
   bei System.Windows.StyleHelper.GetInstanceValue(UncommonField`1 dataField, DependencyObject container, FrameworkElement feChild, FrameworkContentElement fceChild, Int32 childIndex, DependencyProperty dp, Int32 i, EffectiveValueEntry& entry)  
   bei System.Windows.StyleHelper.GetChildValueHelper(UncommonField`1 dataField, ItemStructList`1& valueLookupList, DependencyProperty dp, DependencyObject container, FrameworkObject child, Int32 childIndex, Boolean styleLookup, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)  
   bei System.Windows.StyleHelper.GetChildValue(UncommonField`1 dataField, DependencyObject container, Int32 childIndex, FrameworkObject child, DependencyProperty dp, FrugalStructList`1& childRecordFromChildIndex, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)  
   bei System.Windows.StyleHelper.GetValueFromStyleOrTemplate(FrameworkObject fo, DependencyProperty dp, EffectiveValueEntry& entry)  
   bei System.Windows.StyleHelper.ApplyStyleOrTemplateValue(FrameworkObject fo, DependencyProperty dp)  
   bei System.Windows.StyleHelper.InvalidateContainerDependents(DependencyObject container, FrugalStructList`1& exclusionContainerDependents, FrugalStructList`1& oldContainerDependents, FrugalStructList`1& newContainerDependents)  
   bei System.Windows.StyleHelper.DoStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle)  
   bei System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)  
   bei System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)  
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)  
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)  
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)  
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)  
   bei System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)  
   bei System.Windows.FrameworkElement.UpdateStyleProperty()  
   bei System.Windows.FrameworkElement.OnInitialized(EventArgs e)  
   bei System.Windows.FrameworkElement.TryFireInitialized()  
   bei System.Windows.FrameworkElement.AddLogicalChild(Object child)  
   bei System.Windows.Controls.ContentControl.OnContentChanged(Object oldContent, Object newContent)  
   bei System.Windows.Controls.ContentControl.OnContentChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)  
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)  
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)  
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)  
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)  
   bei System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)  
   bei System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)  
   bei System.Windows.Controls.ContentControl.set_Content(Object value)  
   ... USERCODE ...  
   bei MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)  
   bei System.Windows.Controls.Primitives.ButtonBase.OnClick()  
   bei System.Windows.Controls.Button.OnClick()  
   bei System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)  
   bei System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)  
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)  
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)  
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)  
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)  
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)  
   bei System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)  
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)  
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)  
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)  
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)  
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)  
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)  
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)  
   bei System.Windows.Input.InputManager.ProcessStagingArea()  
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)  
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)  
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)  
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)  
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)  
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)  
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)  
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)  
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Brehme** [comment]
I found the root cause and can even provide a working example. But it has nothing to do with snoop. The exception occures only because snoop is attached as debugger. In that case WPF tries to build a trace message and uses AvTrace.AntiFormat to create string for the SourceProperty of value null. 
I think you can close that issue.

**Comment by batzen** [comment]
You might want to report it at the WPF repo then.
