### ISSUE TITLE
Process dropdown refresh is extremely slow to refresh and display

### ISSUE THREAD

**Issue by NickHarmer** [snoopwpf/snoopwpf#309]
On my system, clicking the 'refresh' button on the toolbar takes over a minute to populate the list of applications, even when there are a relatively small number of them.

Even clicking the drop-down button to display the list after it has been populated takes more than five seconds.

Is there anything we can do to improve this?

------

Windows 11

**Comment by batzen** [comment]
Which version of Snoop are you using?

**Comment by batzen** [comment]
Checked this yesterday with version 4 of Snoop.  Opening the drop-down and refreshing were nearly instant on my machine, which also runs on win11.

**Comment by batzen** [comment]
@NickHarmer Any details you can provide?
