### ISSUE TITLE
Click on a WPF button

### ISSUE THREAD

**Issue by fiddyschmitt** [snoopwpf/snoopwpf#322]
Hi,

Thanks for the great project. Using Snoop I'm able to navigate to the `ButtonControl` I'm interested in. Is there a way to issue a click command on that button?

Thank you,
Fidel

**Comment by batzen** [comment]
@fiddyschmitt Sorry for the late response.
You can use the "Methods" tab to invoke methods on objects, or you can use the "PowerShell" tab.
Aside from that there are not UI automation features (except viewing the automation tree) in Snoop and in don't plan to add automation features.
