### ISSUE TITLE
[Bug] Ctrl+Shift mouseover, Order of releasing keys changes behavior

### ISSUE THREAD

**Issue by mikechristiansenvae** [snoopwpf/snoopwpf#355]
### Summary

When using the `Ctrl+Shift` mouseover feature, the behavior of Snoop differs depending on if you release the `Ctrl` key or the `Shift` key first.

### Test Project

[Git repository](https://gitlab.com/michael.christiansen/snoopbug)

![image](https://user-images.githubusercontent.com/55414409/178302174-a1d23d82-74b7-49c6-990b-702de80a695a.png)

```xml
<GroupBox BorderBrush="Black"
          BorderThickness="1"
          Header="This is a groupbox header"
          >
    <TextBlock TextWrapping="Wrap" MaxWidth="600">Lorem ipsum dolor sit...</TextBlock>
</GroupBox>
```

**Note:** In the test repo, a custom style is applied to the `GroupBox`, but the bug persists even without the custom style

### Steps to replicate

**Release `Control` first**

1. Hold the `Control` key
2. Hold the `Shift` key
3. Mouseover the `TextBlock` in the `GroupBox` header
4. Snoop shows that the `TextBlock` is the selected item in the visual tree (_as expected_)
5. Release the `Control` key
6. Release the `Shift` key
7. Snoop shows that the `TextBlock` is the selected item in the visual tree (_as expected_)

**Release `Shift` first**

1. Hold the `Control` key
2. Hold the `Shift` key
3. Mouseover the `TextBlock` in the `GroupBox` header
4. Snoop shows that the `TextBlock` is the selected item in the visual tree (_as expected_)
5. Release the `Shift` key
6. Snoop changes to show that the `GroupBox` is the selected item* in the visual tree (**NOT** expected)
7. Release the `Control` key
8. Snoop still shows that the `GroupBox` is the selected item* in the visual tree (**NOT** expected)

\* Note: It seems that if the `GroupBox` is the child of the `Window`, that the `Window` is becomes the selected item in the visual tree.  If the `GroupBox` is the child of another control, like a `Grid` (as in the test repository I linked to), then the `GroupBox` becomes the selected item.

**Comment by batzen** [comment]
Could you try this with the latest ci build?
I removed the single handling of CTRL and replaced it with tracking options in the menu.
![image](https://user-images.githubusercontent.com/1971030/178318650-13fd4fd8-d172-4f5c-b851-01af55534760.png)
