### ISSUE TITLE
How to view attached properties?

### ISSUE THREAD

**Issue by matthew-a-thomas** [snoopwpf/snoopwpf#357]
I just installed 4.0.1 after updating to Windows 11. I don't recall what version of Snoop I was running before that, but I seem to recall being able to view the values of attached properties like `Canvas.Top`. Is that possible to do in 4.0.1?

**Comment by batzen** [comment]
Sorry for my late response. Thought i had answered...

It should be possible to view Canvas properties.
If your control is inside a Canvas they should be visible.
