### ISSUE TITLE
Crash when browser the visual tree

### ISSUE THREAD

**Issue by woodxiang** [snoopwpf/snoopwpf#36]
Message: 异常来自 HRESULT:0xD4B66448
Stacktrace:
   在 MS.Win32.UnsafeNativeMethods.ITextStoreACPSink.OnLayoutChange(TsLayoutCode lcode, Int32 viewCookie)
   在 System.Windows.Documents.TextStore.OnLayoutUpdated()
   在 System.Windows.Documents.TextEditor.OnTextViewUpdatedWorker(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MaciekRakowski** [comment]
Sorry for the late reply. Is there anyway you can send an app that reproduces the issue?

**Comment by woodxiang** [comment]
I can not reproduce this issue anymore.
