### ISSUE TITLE
没有足够的内存继续执行程序。

### ISSUE THREAD

**Issue by xwg1984** [snoopwpf/snoopwpf#360]
**Place your issue description here.**

Exception details:
System.OutOfMemoryException: 没有足够的内存继续执行程序。
   在 System.Windows.Media.Imaging.RenderTargetBitmap.FinalizeCreation()
   在 System.Windows.Media.Imaging.RenderTargetBitmap..ctor(Int32 pixelWidth, Int32 pixelHeight, Double dpiX, Double dpiY, PixelFormat pixelFormat)
   在 Snoop.Infrastructure.VisualCaptureUtil.RenderVisual(Visual visual, Size bounds, Int32 dpiX, Int32 dpiY, Nullable`1 pixelFormat, Viewport3D viewport3D) 位置 C:\projects\snoopwpf\Snoop.Core\Infrastructure\VisualCaptureUtil.cs:行号 97
   在 Snoop.Controls.VisualTree3DView.MakeBrushFromVisual(Visual visual, Rect bounds, Int32 dpi) 位置 C:\projects\snoopwpf\Snoop.Core\Controls\VisualTree3DView.cs:行号 208
   在 Snoop.Controls.VisualTree3DView.ConvertVisualToModel3D(Visual visual, Int32 dpi, Double& z) 位置 C:\projects\snoopwpf\Snoop.Core\Controls\VisualTree3DView.cs:行号 119
   在 Snoop.Controls.VisualTree3DView.ConvertVisualToModel3D(Visual visual, Int32 dpi, Double& z) 位置 C:\projects\snoopwpf\Snoop.Core\Controls\VisualTree3DView.cs:行号 144
   在 Snoop.Controls.VisualTree3DView.ConvertVisualToModel3D(Visual visual, Int32 dpi, Double& z) 位置 C:\projects\snoopwpf\Snoop.Core\Controls\VisualTree3DView.cs:行号 144
   在 Snoop.Controls.VisualTree3DView..ctor(Visual visual, Int32 dpi) 位置 C:\projects\snoopwpf\Snoop.Core\Controls\VisualTree3DView.cs:行号 30
   在 Snoop.Windows.Zoomer.CreateAndSetVisualTree3DView(Visual visual) 位置 C:\projects\snoopwpf\Snoop.Core\Windows\Zoomer.xaml.cs:行号 244
   在 Snoop.Windows.Zoomer.HandleSwitchTo3D(Object sender, ExecutedRoutedEventArgs args) 位置 C:\projects\snoopwpf\Snoop.Core\Windows\Zoomer.xaml.cs:行号 230
   在 System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   在 System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   在 System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   在 System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   在 System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   在 System.Windows.UIElement.OnExecutedThunk(Object sender, ExecutedRoutedEventArgs e)
   在 System.Windows.Input.ExecutedRoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object target)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   在 System.Windows.Input.RoutedCommand.ExecuteCore(Object parameter, IInputElement target, Boolean userInitiated)
   在 MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   在 System.Windows.Controls.Primitives.ToggleButton.OnClick()
   在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   在 System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Wi
Exception details truncated at 4000 chars.

---
### Environment
- Snoop 4.0.0.0
- Windows 6.3.19043
- .NET Framework 4.0.30319.42000

**Comment by batzen** [comment]
Which application did you try to snoop?
Is it a 32 bit or 64 bit application?

**Comment by xwg1984** [comment]
64 bit application
