### ISSUE TITLE
Unhandled InvalidCastException when running on .NET 7

### ISSUE THREAD

**Issue by binarycow** [snoopwpf/snoopwpf#374]
On v4.0.1

![image](https://user-images.githubusercontent.com/37249876/193479675-90438ecd-ad44-4813-91d2-e367fdfe3195.png)

**Comment by batzen** [comment]
Will investigate and ensure that exceptions from diagnostic providers don't crash the application, but are reported as diagnostic items instead.

**Comment by batzen** [comment]
The type was changed in .NET 7 via https://github.com/dotnet/runtime/commit/826896f0ebd4572ab399b4cadc1f208c676cb3c7
