### ISSUE TITLE
Invoke Button Click and Fill TextBox

### ISSUE THREAD

**Issue by AnassKartit** [snoopwpf/snoopwpf#377]
Hi @batzen,
is it possible to post a sample on how to invoke button click with an automationid or automationname through injector?
Thank you

**Comment by batzen** [comment]
Have a look at https://github.com/snoopwpf/snoopwpf/tree/develop/TestHarnesses/SimpleUIAutomation.Application and https://github.com/snoopwpf/snoopwpf/tree/develop/TestHarnesses/SimpleUIAutomation
