### ISSUE TITLE
Export tree

### ISSUE THREAD

**Issue by amake** [snoopwpf/snoopwpf#38]
(Continuing discussion from https://snoopwpf.codeplex.com/discussions/441911)

Has there been any progress on this issue? I would be very happy if I could export the tree to anything, including plain old XML.

(My goal is to get the exact displayed text strings and their bounding boxes within the window; I don't mind calculating the bboxes from ancestor data.)

**Comment by lunafutures** [comment]
In addition, it'd also be nice to just export the elements and values of a single node in the tree.
