### ISSUE TITLE
Light mode broken

### ISSUE THREAD

**Issue by mo-russo** [snoopwpf/snoopwpf#397]
It looks like this on my machine:

![image](https://user-images.githubusercontent.com/74058706/219059468-3fdf0c55-354d-47b4-9c46-2da2780ae450.png)

**Comment by mo-russo** [comment]
I just upgrade to the latest this morning, started my application, snooped it and it was like that. Didn't do anything special.
The Dark mode works properly though which I'm using right now as a workaround.

**Comment by mo-russo** [comment]
Unfortunately no, it's not my application but my employer's. I can't distribute it.

**Comment by batzen** [comment]
Could you try to use the debug menu in Snoop and choose "Snoop Snoop".
After that inspect the Snoop UI itself, have a look at the foreground property of one of the elements in the grid which has a wrong foreground?
The foreground should reference to the resource key "Snoop.Brushes.Default.Foreground".
Something in your application seems to influence that value.

**Comment by batzen** [comment]
@NMBSdtayloe @mo-russo Have you tried the above to provide some information on the cause for this issue?

**Comment by NMBSdtayloe** [comment]
@batzen Can you provide some guidance for how and where this value would be found? I did "Snoop Snoop" and this is maybe what you are looking for. I put a red box around the foreground brush you mentioned.
![image](https://github.com/snoopwpf/snoopwpf/assets/113055594/5de667c6-7341-4963-958f-2595c4eab8fd)

**Comment by batzen** [comment]
@NMBSdtayloe You have to inspect the TextBlock which has the wrong foreground while in dark mode and being attached to your application.

**Comment by NMBSdtayloe** [comment]
These are some of the instances of textblock in my app. I apologize in advance, I do not have any experience in using snoop or digging through the treeview of a WPF app. I searched for textblock again later and somehow got more results and sometimes just a flat list or it selects the first random textblock it finds.
![image](https://github.com/snoopwpf/snoopwpf/assets/113055594/90504dc0-2a50-406f-976e-d1325c705d4b)

**Comment by batzen** [comment]
I changed quite a lot of the theme code etc. So it's most likely a regression, but as long as there is no repro I can't fix it as it happens with none of the apps I tried.
@EgilSandfeld do you have a repro?

**Comment by batzen** [comment]
@EgilSandfeld @mo-russo @NMBSdtayloe ping

**Comment by joce** [comment]
@batzen Have you made any progress on this? I'm having the same issue.
However, same as the other users, I can't distribute the app I'm snooping, but I'm willing to help.

**Comment by joce** [comment]
Err. Even doing Snoop Snoop, I get the same issue!

![image](https://github.com/snoopwpf/snoopwpf/assets/80361/6092af3a-6ef4-48d3-9e11-577c10baa49e)

**Comment by joce** [comment]
As others pointed out, it works fine when in Dark Mode on my side as well.

![image](https://github.com/snoopwpf/snoopwpf/assets/80361/7d79fe0c-13b2-4ccb-a957-1d2dddb9efdf)

Can't you repro when you're in default app mode is Light Mode?

**Comment by batzen** [comment]
This is what i get when using light mode system wide and attaching Snoop:
![image](https://github.com/snoopwpf/snoopwpf/assets/1971030/a78cc371-bd4f-422c-9352-7a49586051e2)

**Comment by joce** [comment]
Interesting.
I DM'd you on twitter to book a Zoom appointment.

**Comment by batzen** [comment]
@joce Our call was very helpful.
I finally found a way to reproduce the issue.
