### ISSUE TITLE
Cannot attach the snoop to the .net framework 4.5 single app

### ISSUE THREAD

**Issue by manavmehta2403** [snoopwpf/snoopwpf#398]
![image](https://user-images.githubusercontent.com/50082167/219551774-5e4f75fe-f290-4ddc-9c58-393cbee8ad4a.png)

The error in the log

**Comment by batzen** [comment]
Which exact .NET version are you using?
Which Snoop version are you using?
Does this happen every time you try to attach to your application?
Can you share your application?

**Comment by manavmehta2403** [comment]
.NET 4.5 
Snoop version 5 and also 4 and 2.11 
It happens every time... earlier I need to uninstall windows update .NET cumulative. .Net3/.net4/.net5 update to make this work
But, I cannot uninstall the windows update, and this throws the error,
I am sorry it is confidential application

**Comment by batzen** [comment]
As the exception occurs deep inside of WPF and a windows update causes the issue you should report it to Microsoft. If they broke something in WPF there is little I can do to fix it.

Which windows update causes your issue on which windows version?

**Comment by manavmehta2403** [comment]
![image](https://user-images.githubusercontent.com/50082167/219583510-dd89b171-21dc-40c5-8cc1-079c545b1d26.png)
https://support.microsoft.com/en-us/topic/december-13-2022-kb5021090-cumulative-update-for-net-framework-3-5-4-8-and-4-8-1-for-windows-11-bad8107d-25df-4cdc-8043-2779893aa1c8

for windows 11

**Comment by batzen** [comment]
Could you try to debug your application while attaching and check what kind of item gets added when the crash occurs and if it's always the same item?

**Comment by manavmehta2403** [comment]
![image](https://user-images.githubusercontent.com/50082167/220379131-8df4fd15-a274-4258-a233-cbf94dc728a5.png)

**Comment by batzen** [comment]
That's not very useful.

You have to let the debugger stop where the exception really happens.
This might require disabling "Enable just my code", enabling "Enable .NET Framework source stepping" and adding the Microsoft Symbol Server as a symbol source in the debug settings.

And you might have to enable break on all exceptions in the exception settings.

You might even have to disable your exception handler, but i am not sure about that.

**Comment by manavmehta2403** [comment]
hey I am able to fix the issue by downloading the specific program mentioned in the above URL 
Although I am attaching the URL of the program too.
Thanks
https://support.microsoft.com/en-us/topic/kb5022083-change-in-how-wpf-based-applications-render-xps-documents-a4ae4fa4-bc58-4c37-acdd-5eebc4e34556
