### ISSUE TITLE
Save the Current Preview to file does not work all the time

### ISSUE THREAD

**Issue by tisis2** [snoopwpf/snoopwpf#399]
often when i use the feature no file exists afterwards and no error pops up. on the debug console i see the message: 
```
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:(no path); DataItem=null; target element is 'VisualBrush' (HashCode=24157832); target property is 'Visual' (type 'Visual')
```

**Comment by batzen** [comment]
A few more details like:
Which version of Snoop are you using?
Which application does this happen with?
Is it always the same visual?
Does the preview render correctly?

**Comment by tisis2** [comment]
> A few more details like the following would be nice.
> 
> Which version of Snoop are you using?

first i used 4.0.0 then i saw there is a 5.0.1 and updated but same issur there

> Which application does this happen with?

none official. i can try to see if i am able to reproduce it in a sample tomorrow

> Is it always the same visual?

i had the issue with several different controls
> Does the preview render correctly?

yes

**Comment by tisis2** [comment]
i did not create a sample project. instead i tried to just reproduce the issue with snoop itself and was able to reproduce.
![gif_38](https://user-images.githubusercontent.com/18416393/220543658-e99a58f7-8f6e-4aa3-b5ef-c657e69fc6a0.gif)

**Comment by batzen** [comment]
Will have a look as soon as I can.
