### ISSUE TITLE
Snoop does not show version

### ISSUE THREAD

**Issue by jhv2017kam** [snoopwpf/snoopwpf#404]
**Place your issue description here.**

How do I know if my version is up to date / what version of snoopwpf I am using
The only dialog I can open from the window is the settings dialog and it does not show version

**Please do not include large amounts of code in your issue. Please attach a zip file containing a repro instead.**

---
### Environment

- Snoop __v?.?.?__
- Windows __?__
- .NET Framework __?.?__

**Comment by batzen** [comment]
That's a very good point.
