### ISSUE TITLE
Add mention about SignPath Foundation and free code certificate in Readme.md

### ISSUE THREAD

**Issue by SabotageAndi** [snoopwpf/snoopwpf#409]
Hi

First, thanks for maintaining this tool! I used it a lot in the past!

Now I am the Developer Evangelist from SignPath and I noticed that there is no mention of us in the readme. 
Could you please add this to your Readme:

```
## Code Signing
This program uses free code signing provided by [SignPath.io](https://signpath.io?utm_source=foundation&utm_medium=github&utm_campaign=snoopwpf), and a free code signing certificate by the [SignPath Foundation](https://signpath.org?utm_source=foundation&utm_medium=github&utm_campaign=snoopwpf)
```

If you want, I can send a Pull Request.

Thanks!

**Comment by batzen** [comment]
Thanks for reaching out to me.
I totally forgot to mention SignPath.
Sorry for that and thanks for providing your service for free to Snoop.

I added a slightly modified version of your text to the readme.

**Comment by SabotageAndi** [comment]
All good. No problem. It is fixed now.
Thanks for adding it and for your work on Snoop!
