### ISSUE TITLE
Unable to build if ARM MSVC tools not installed 

### ISSUE THREAD

**Issue by KirillOsenkov** [snoopwpf/snoopwpf#421]
On my machine, Snoop.GenericInjector.vcxproj fails to build for ARM:

```
C:\snoopwpf\Snoop.GenericInjector\dllmain.cpp error C2220: the following warning is treated as an error [C:\snoopwpf\Snoop.GenericInjector\Snoop.GenericInjector.vcxproj]
c1xx error C1250: Unable to load plug-in 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX86\arm\EspXEngine.dll'. 
```

My `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\Hostx86\` directory only contains x64 and x86 subdirectories.

Should we perhaps condition the ARM and ARM64 builds here based on whether the ARM tools are installed?

https://github.com/snoopwpf/snoopwpf/blob/d64e447e81fa051e7273089027a7b5914dc0e473/Snoop.GenericInjector/Snoop.GenericInjector.vcxproj#L155-L156

**Comment by KirillOsenkov** [comment]
Proposed fix in https://github.com/snoopwpf/snoopwpf/pull/422

**Comment by batzen** [comment]
It's listed in the build requirements and there is a .vsconfig file listing it as a requirement, i don't think conditioning is required.
Why do you think it's an issue to be required to have those installed?
