### ISSUE TITLE
keyboard not working in snoop window

### ISSUE THREAD

**Issue by gottscbe** [snoopwpf/snoopwpf#426]
Only typing letters and numbers is impossible.
When using tab or CTRL+V, this works.

---
### Environment

- Snoop __v5.0.0__
- Windows __10__
- .NET Framework __?.?__

**Comment by batzen** [comment]
I never experienced such an issue.
Could you provide a sample app where this happens?

**Comment by batzen** [comment]
@gottscbe ping

**Comment by gottscbe** [comment]
Sorry, we could identify the problem at our side. It is no issue in snoop.Am 03.10.2023 um 11:31 schrieb Bastian Schmidt ***@***.***>:﻿
@gottscbe ping
