### ISSUE TITLE
Unable to compile from source code

### ISSUE THREAD

**Issue by arkoste** [snoopwpf/snoopwpf#438]
I'm not albe to build from source code

I've downloaded source code from here https://github.com/snoopwpf/snoopwpf/releases

After open the solution from vs2022, it prompted to me to install some features

When i try to build i receive lots of errors due to missed .h files like this (and others)

2>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xiosbase(10,10): error C1083: Cannot open include file: 'share.h': No such file or directory

Indee the directory is not present in my file system like others!

What i'm doing wrong?

I've inported .vsconfig as suggested but nothing needs to be added to my actual configuration

- Snoop 5.1.0
- Windows 11
- .NET Framework 4.5.2

**Comment by batzen** [comment]
I rarely setup a new machine, so there i might have forgotten to add something to the config file.
Will try to find out what's missing.

**Comment by batzen** [comment]
I just tested this in a Windows Sandbox using a clean install of VS 2022 17.8.3 Community.
Everything compiles as it should (except a missing .NET SDK version error for SDK 6.0.400 and a new warning when using .NET SDK 8.0).

Which version of Visual Studio are you using?
On my machine `share.h` is located in `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\share.h`.
Maybe your Windows SDK install is broken?

**Comment by arkoste** [comment]
All c# projects are ok. I'm also able to start the application with F5
I have only a problem with Snoop.GenericInjector
It gives me the error C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\**xiosbase**(10,10): error C1083: Cannot open include file: 'share.h': No such file or directory

After specifying the path C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt in Project Include Directory, the message is gone but i receive a liker error:

1>LINK : fatal error LNK1104: cannot open file 'libucrtd.lib'

Sorry but i'm not a C++ guy!

**Comment by batzen** [comment]
`libucrtd.lib` should be located in architecture specific directories `x86`, `x64`, `arm` and `arm64` inside `C:\Program Files (x86)\Windows Kits\10\lib\SOME_VERSION\ucrt`.

In my case it looks like this:
![image](https://github.com/snoopwpf/snoopwpf/assets/1971030/1d366f35-66e6-47a6-9df8-792529146630)

I still guess something is wrong with your Windows SDK install.
Could you try to do a repair install of Visual Studio or the SDK if you installed it manually?

**Comment by arkoste** [comment]
ye yes, i did but if i add the x86 path to Poject Library Directory like this `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x86;$(LibraryPath)`, the linker told me that is unable to find Kernel32.dll!

```
Error	LNK1181	cannot open input file 'kernel32.lib'
```		


Maybe i have to repair the vs installation!

**Comment by batzen** [comment]
That's very strange.
There should be no need to specify any include or library paths.

I tested with an Windows Sandbox and everything worked as expected.

I think there isn't much i can do, aside from guessing your VS installation or something else on your system is faulty.

You could try to do a build with diagnostic verbosity and attach the log as a file here.
Maybe i can see something in the log that helps to find out what's wrong with your system.

**Comment by arkoste** [comment]
[log.txt](https://github.com/snoopwpf/snoopwpf/files/13743506/log.txt)

this is the log

**Comment by arkoste** [comment]
I want to report what i've done on my notebook with win11 pro and vs2022 17.8.3:

1) Uninstall vs2022
2) Reboot
3) Install vs2022 with this configuration 
[vsconfig.txt](https://github.com/snoopwpf/snoopwpf/files/13745255/vsconfig.txt)
4) Open the project AND NOT INSTALL WHAT SUGGESTED

![image](https://github.com/snoopwpf/snoopwpf/assets/13915247/9e724b45-3fc1-4469-bb4d-c1097e09f1e3)

**This way i'm able to compile the C++ project with no errors**

If i install what vs2022 suggests, i won't be able to compile it anymore.

I don't know why but if i install what suggested, Include Directory and Library Directory in vs2022 change from this

```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\atlmfc\include
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include
**C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt**
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\Include\um
```

to this:

```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\atlmfc\include
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include
**C:\Program Files\Windows Kits\10\Include\10.0.22621.0\ucrt**
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\Include\um
```

The 4th entry doesn't not exists!

**Comment by batzen** [comment]
I added an additional Windows 11 SDK to the .vsconfig to hopefully fix the issue.
It also got installed on my clean machine (Sandbox) even though it wasn't listed in the .vsconfig file.
Maybe the installer behaves different if installing on a clean machine vs a machine where it was once installed...

**Comment by arkoste** [comment]
Thank you.
I think this can be closed
