### ISSUE TITLE
Installer: "Installation directory must be on a local hard drive"

### ISSUE THREAD

**Issue by mathdons** [snoopwpf/snoopwpf#442]
Using the latest .msi, the installer reports "Installation directory must be on a local hard drive" and fails to install. 
Tested on Win 10, default path "C:\Program Files (x86)\Snoop\", as well as "C:\Snoop\", "D:\Snoop"

The zipped portable version works just fine.

**Comment by batzen** [comment]
Does the installer prompt for elevation when you click "Install" or at which point during the installation does it show that error?

**Comment by mathdons** [comment]
> Does the installer prompt for elevation when you click "Install" or at which point during the installation does it show that error?
It does not.

**Comment by batzen** [comment]
That's strange as it should prompt for elevation.
Could you try to run an elevated command prompt and start the MSI from there?

**Comment by mathdons** [comment]
Same thing from elevated cmd or PS, doesn't prompt, same message.

**Comment by batzen** [comment]
That makes no sense to me.
Could you run the installer with verbose logging enabled and attach the log here?
You can enable verbose logging by calling the installer from a command prompt using
`msiexec /i Snoop.5.1.0.msi /L*vx "C:\ExampleLogFilename.txt"`

**Comment by mathdons** [comment]
Sure, here it is, ran from elevated cmd.
[msilog.txt](https://github.com/snoopwpf/snoopwpf/files/14484282/msilog.txt)

**Comment by batzen** [comment]
That looks like an bug in WiX/MSI itself as it's not even logging what failed during `ValidatePath`.
What's also strange is that ValidatePath returns 1 (success) but does not set WIXUI_INSTALLDIR_VALID to 1.

Maybe you can launch dbgview when running the installer as the installer should also output trace messages there.
