### ISSUE TITLE
Keystrokes go to Visual Studio main window when inspecting Visual Studio

### ISSUE THREAD

**Issue by KirillOsenkov** [snoopwpf/snoopwpf#45]
Could someone please confirm if they're seeing the same behavior:
1. Open a new instance of Visual Studio
2. Open Snoop, inspect the instance of Visual Studio from step 1
3. Ctrl+Shift and move mouse over some VS element, such as a toolbar button
4. Go to Snoop, select Powershell, type $selected and press ENTER

Expected: 
ENTER should commit the command into Powershell.

Actual: 
ENTER goes to Visual Studio main window, and if the editor in VS is open, it sends enter there.

If this is indeed a bug that others are seeing, then I have a pull request ready that fixes this:
#44

**Comment by gix** [comment]
I can confirm this (annoying) behavior.

**Comment by Newrad0603** [comment]
Confirmed still happens in 2.11. Specifically, it's just a subset of keystrokes that go to VS: Enter, Backspace being two of the most impactful key presses being routed to VS.

**Comment by batzen** [comment]
Will have a look at this. Hopefully during the weekend.

**Comment by batzen** [comment]
Fixed in develop branch.
