### ISSUE TITLE
ExecuteInDefaultAppDomain Returns with file not found when injecting into Visual Studio 2022

### ISSUE THREAD

**Issue by ZD-FLoM** [snoopwpf/snoopwpf#465]
I am trying to follow the TestHarnesses sample but instead dynamically inject into an external application. The injection works up to ExecuteInDefaultAppDomain. Recieved hr translates to 0x80070002

Received "2147942402" from injector component.
##############################################
Log from injector component:
##############################################
net462<|>C:\Users\Guest\source\repos\UIAutomation\InjectedClicker\bin\Debug\net8.0-windows10.0.20348.0\InjectedClicker.dll<|>InjectedClicker.Clicker<|>StartAutomation<|>C:\Users\Guest\AppData\Local\Temp\tmpha0pgo.tmp<|>C:\Users\Guest\AppData\Local\Temp\tmp938.tmp
Trying to get executor for framework 'net462'...
NetFull4_0Executor: Trying to get runtime meta host...
NetFull4_0Executor: Got runtime meta host.
NetFull4_0Executor: Trying to get runtime info...
NetFull4_0Executor: Got runtime info.
NetFull4_0Executor: Trying to get runtime host...
NetFull4_0Executor: Got runtime host.
NetFull4_0Executor: Trying to ExecuteInDefaultAppDomain...

I added more logs here and compiled to double check the passed in strings

NetFull4_0Executor: C:\Users\Guest\source\repos\UIAutomation\InjectedClicker\bin\Debug\net8.0-windows10.0.20348.0\InjectedClicker.dll
NetFull4_0Executor: InjectedClicker.Clicker
NetFull4_0Executor: StartAutomation
NetFull4_0Executor: C:\Users\Guest\AppData\Local\Temp\tmpha0pgo.tmp

NetFull4_0Executor: ExecuteInDefaultAppDomain finished.
Error while calling 'StartAutomation' on 'InjectedClicker.Clicker' from 'C:\Users\Guest\source\repos\UIAutomation\InjectedClicker\bin\Debug\net8.0-windows10.0.20348.0\InjectedClicker.dll' with 'C:\Users\Guest\AppData\Local\Temp\tmpha0pgo.tmp'
HResult: -2147024894
Message: The system cannot find the file specified.

All the previous checks succesfully allocate memory in the foreign application (devenv.exe, Visual Studio 2022). My goal is to read data from the IDE itself. The full Snoop GUI can attach to VS2022.

What I have tested:

Snoop 5.1.0 injector and also compiled from develop branch
TestHarnesses with the SimpleUIAutomation application works out of the box with CORE3.1 and NET8.0
I have tried with and without InjectedClicker.dll registered in GAC
I have tried my own app compiled in net4.6.2, injectedclicker.dll compiled targeting 4.6.2 and injecting into VS2022
I have tried Any CPU and x64
I have tried x86 targeting VS2019, same issue
Running the app as Administrator

There are no details as to what file is not found specifically from ExecuteInDefaultAppDomain. All listed files are present. I am not sure what I am missing. Running from the custom build Snoop Injector also prints all the DLLs loaded under each devenv process, showing the VS2019 or VS2022 assemblies are loaded. 

---
### Environment

- Snoop __v5.1.0__
- Windows __21H2 OS Build 19044.5011__
- .NET Framework __8.0__

**Comment by batzen** [comment]
You could try to run procmon, from the sysinternals suite, to diagnose which file is being tried to load.

Or you could attach a debugger to your target process, in your case you need two visual studio instances, and change the exception settings to halt on all managed and unmanaged exceptions. When attaching the debugger don't forget to set the debug mode to manually and select native and managed.

Hope that helps.

**Comment by ZD-FLoM** [comment]
I have been unable to find a way to see what the Target Framework is for an application after it has been injected. For an unknown application, it would be nice for the Snoop Injector to figure out which target runtime is needed for the user's custom injected dll and then use that specific Framework Target build dll. 

I ended up finding a .config file within VS2019's IDE folder that shows a legacy target framework as 4.7.2. After building against my automation driver as 4.7.2, I no longer receive a file not found expectation. 

A side effect of building with 4.7.2 was removing the implicit global usings .NET 8 offers. I am not sure if this is related. I will move back to VS2022 and test x64 bit.

**Comment by batzen** [comment]
Ah, sorry. Overlooked that you are trying inject a .NET 8 DLL into Studio.
That doesn't work, of course.
It makes no sense for the injector to choose the target framework based on the user supplied DLL instead of the target process as that wouldn't work either.
But the injector could try to figure out if the supplied DLL is compatible with the target process.
Not sure if it's worth the effort.
