### ISSUE TITLE
Keyboard events not passed to snoop UI window

### ISSUE THREAD

**Issue by IgorMarkovic** [snoopwpf/snoopwpf#55]
I have a mixed WinForms and WPF app. During the initialization of the Winforms app I already initialize WPF:
`
new System.Windows.Application { ShutdownMode = System.Windows.ShutdownMode.OnExplicitShutdown };
`

This results in that FindRoot in SnoopUI.xaml.cs thinks it's an WPF application:

`
if (Application.Current != null) { }
`

This prevents the execution of the else statement which enabled keyboard interop for modeless WPF windows in winforms applications: ElementHost.EnableModelessKeyboardInterop(this);

Why not move this code outside the else statement:

`
            if (System.Windows.Forms.Application.OpenForms.Count > 0)
            {
                // this is windows forms -> wpf interop

                // call ElementHost.EnableModelessKeyboardInterop to allow the Snoop UI window
                // to receive keyboard messages. if you don't call this method,
                // you will be unable to edit properties in the property grid for windows forms interop.
                ElementHost.EnableModelessKeyboardInterop(this);
            }
`

**Comment by batzen** [comment]
This was fixed with #118.
