### ISSUE TITLE
.NETCore 3.0 support

### ISSUE THREAD

**Issue by rido-min** [snoopwpf/snoopwpf#98]
Do you have any plans to support .NETCore3.0 ? Current version (2.10.0.0)  fails with:

```
---------------------------
Can't Magnify
---------------------------
Can't find a current application or a PresentationSource root visual!
```

**Comment by batzen** [comment]
I planned working on this as soon as i released Fluent.Ribbon v7.0.

**Comment by alexserov** [comment]
Hi @batzen , I have an injector library based on the ManagedInjector, [you can find the repo here](https://github.com/alexserov/NetInjection). We may use it to implement the feature.

**Comment by batzen** [comment]
I already got it working with ijwhost in the develop branch. But your approach also looks promising and might also work with self contained apps. Will have to try a few things as the main goal was to completely get rid of c++ in snoop and I don't think your approach works without c++.

**Comment by batzen** [comment]
Done.

**Comment by kmukesh2008** [comment]
Hi All,
I have installed 2.11.0.0. I am getting below error.
---------------------------
Can't Snoop
---------------------------
Can't find a current application or a PresentationSource root visual.
---------------------------
OK   
---------------------------

I am trying on WPF Core 3.0.  Could you please suggest me.

**Comment by batzen** [comment]
@kmukesh2008 You need to use/install the preview version of snoop 3.0 to get .net core support.
The final version of snoop 3.0 will be release in the next few weeks.

**Comment by kmukesh2008** [comment]
Thank a lot @batzen for quick response. . I am trying to download snoop 3.0 preview version. It's my bad still i didn't the url to download preview version.

**Comment by batzen** [comment]
@kmukesh2008 you can always download the latest source build from https://ci.appveyor.com/project/batzen/snoopwpf/branch/develop/artifacts
